### ISSUE TITLE
Investigate why some nodes didn't create the storekeys for wasm and superfluid

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1011]
I've seen two different people get an error, where when upgrading to v7 software patch, they didn't get the storekeys for `wasm` and `superfluid` created. This manifests in a panic, as the parameter setting for wasm didn't happen.

One of the parties had this consistently happen on all (three) of their nodes, and never saw the relevant log lines for the store initialization.

These are the log lines we expected to see, for initializing the wasm store:
![image](https://user-images.githubusercontent.com/6440154/156124724-ca1db9d1-9310-4ef7-a687-74e8db26c683.png)

The panic / error seems to me to pretty clearly indicate a root cause of these stores not getting initialized, now we have to understand why.

The panic:
```
{TIME} INF Replay last block using real app module=consensus
{TIME} INF applying upgrade "v7" at height: 3401000
{TIME} INF Start running migrations
panic: UnmarshalJSON cannot decode empty bytes

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/params/types.Subspace.Get({{0x27d4558, 0xc00c21d7a0}, 0xc0000102c8, {0x276dbe0, 0xc00c25c010}, {0x276dc30, 0xc00c25c130}, {0xc00c276420, 0x4, 0x15}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.45.1/x/params/types/subspace.go:109 +0x319
github.com/cosmos/cosmos-sdk/x/params/types.Subspace.GetParamSet({{0x27d4558, 0xc00c21d7a0}, 0xc0000102c8, {0x276dbe0, 0xc00c25c010}, {0x276dc30, 0xc00c25c130}, {0xc00c276420, 0x4, 0x15}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.45.1/x/params/types/subspace.go:222 +0x145
github.com/CosmWasm/wasmd/x/wasm/keeper.Keeper.GetParams(...)
        github.com/CosmWasm/wasmd@v0.23.0/x/wasm/keeper/keeper.go:151
github.com/osmosis-labs/osmosis/v7/app/upgrades/v7.CreateUpgradeHandler.func1({{0x27a9cc8, 0xc00005c050}, {0x27d9d80, 0xc00131ad80}, {{0xb, 0x1}, {0xc22ee26e50, 0x9}, 0x33e528, {0x172958, ...}, ...}, ...}, ...)
        github.com/osmosis-labs/osmosis/v7/app/upgrades/v7/upgrades.go:43 +0x265
github.com/cosmos/cosmos-sdk/x/upgrade/keeper.Keeper.ApplyUpgrade({{0x7ffd049f7be6, 0xd}, 0xc00c1e3740, {0x276dbe0, 0xc00c25c030}, {0x27d4558, 0xc00c21d7a0}, 0xc00c2591a0, {0x275dec0, 0xc0003f96c0}}, ...)
        github.com/cosmos/cosmos-sdk@v0.45.1/x/upgrade/keeper/keeper.go:301 +0x1be
github.com/cosmos/cosmos-sdk/x/upgrade.BeginBlocker({{0x7ffd049f7be6, 0xd}, 0xc00c1e3740, {0x276dbe0, 0xc00c25c030}, {0x27d4558, 0xc00c21d7a0}, 0xc00c2591a0, {0x275dec0, 0xc0003f96c0}}, ...)
        github.com/cosmos/cosmos-sdk@v0.45.1/x/upgrade/abci.go:59 +0x6a5
github.com/cosmos/cosmos-sdk/x/upgrade.AppModule.BeginBlock(...)
        github.com/cosmos/cosmos-sdk@v0.45.1/x/upgrade/module.go:130
<snip>
```

**Comment by ValarDragon** [comment]
No idea what happened here, lets close though since nothing else has ran into this.
