### ISSUE TITLE
wrong Block.Header.AppHash after v8

### ISSUE THREAD

**Issue by carameleon** [osmosis-labs/osmosis#1559]
#### System information

Osmosis version: `Osmosis version`
```
server_name: osmosisd
version: 8.0.0
commit: 16e3b51f19a58f815a4eabcbcee11886eb33e026
build_tags: netgo,ledger
go: go version go1.18.1 linux/amd64
```
OS & Version: Windows/Linux/OSX
```
ubuntu 20.04
uname : Linux #19~20.04.1-Ubuntu SMP Mon Mar 7 12:53:12 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
Commit hash: 

#### Actual behaviour

This node is for processing heavy api requests.
I've got apphash mismatch errors. And only this node has happened 3times since the v8 upgrade.
Also, apphash mismatch has always happened within 10~20min after epoch done.
I guess it is related to LCD usage.

May 15
```
May 15 15:44:50  3:44PM INF received complete proposal block hash=539DD2A4BD9214B4FF7343B2CF42AA0C099D44ABDA948AB04C0B58B32CC0FE4A height=4402000 module=consensus
May 15 15:44:51  3:44PM INF finalizing commit of block hash=539DD2A4BD9214B4FF7343B2CF42AA0C099D44ABDA948AB04C0B58B32CC0FE4A height=4402000 module=consensus num_txs=74 root=00D1F84DBB142BB90805A9D07FA7C1EF6CF1AE8CB7B10F7A187925566E66712E
May 15 15:44:51  3:44PM INF I am upgrading to v8
May 15 15:44:51  message repeated 99 times: [ 3:44PM INF I am upgrading to v8]
May 15 15:44:51  3:44PM INF Applying Osmosis v8 upgrade. Allowing direct unpooling for whitelisted pools
May 15 15:44:51  3:44PM INF Applying accelerated incentive updates per proposal 225
May 15 15:44:51  3:44PM INF Applying proposal 222 update
May 15 15:44:51  3:44PM INF Applying proposal 223 update
May 15 15:44:51  3:44PM INF Applying proposal 224 update
...
...
May 15 15:44:51  3:44PM INF indexed block height=4402000 module=txindex

May 15 16:41:56  4:41PM INF creating state snapshot height=4402500
May 15 17:10:45  5:10PM INF completed state snapshot format=1 height=4402500

May 15 17:16:45  5:16PM INF Starting epoch with identifier day epoch number 331 module=x/epochs
May 15 17:16:46  5:16PM INF Move delegation rewards to gauges
May 15 17:16:46  5:16PM ERR no delegation distribution info
May 15 17:16:46  message repeated 4 times: [ 5:16PM ERR no delegation distribution info]
May 15 17:16:46  5:16PM ERR no delegation distribution info
May 15 17:16:46  message repeated 20 times: [ 5:16PM ERR no delegation distribution info]
May 15 17:16:46  5:16PM ERR no delegation distribution info
May 15 17:16:46  5:16PM ERR no delegation distribution info
May 15 17:16:46  5:16PM ERR no delegation distribution info
May 15 17:16:46  message repeated 2 times: [ 5:16PM ERR no delegation distribution info]
May 15 17:16:46  5:16PM INF Distribute Superfluid gauges

May 15 17:22:53  5:22PM INF indexed block height=4402822 module=txindex

May 15 17:23:04  5:23PM INF received proposal module=consensus proposal={"Type":32,"block_id":{"hash":"E50B26A28BE97B5BF54FDBE2B43B4A08056F146215D3A94F21B81D1CF9053545","parts":{"hash":"30E299F0A2D56EFFCB118794CE0E2AD30626F83679DB54344493BD82AE6128E3","total":6}},"height":4402823,"pol_round":-1,"round":1,"signature":"AQoknxqGakx+xx0Cyv8zKin3So8O8dOznOycZlnJeme0BLg4MKgqHKBSHIDHu2iK+555y4bs8d/RXS//ib3PCw==","timestamp":"2022-05-15T17:23:03.614067827Z"}
May 15 17:23:05  5:23PM INF received complete proposal block hash=E50B26A28BE97B5BF54FDBE2B43B4A08056F146215D3A94F21B81D1CF9053545 height=4402823 module=consensus
May 15 17:23:05  5:23PM ERR prevote step: ProposalBlock is invalid err="wrong Block.Header.AppHash.  Expected 475121BA2E909AA56AECCFF1BA30581BDB37961F94BF3FFAFE370116BC15D8F3, got 2B90C7310BC7737D621539B01779987FCE199358C339DCECB77FFD33B2FC9BAC" height=4402823 module=consensus round=1
May 15 17:23:05  5:23PM ERR CONSENSUS FAILURE!!! err="precommit step; +2/3 prevoted for an invalid block: wrong Block.Header.AppHash.  Expected 475121BA2E909AA56AECCFF1BA30581BDB37961F94BF3FFAFE370116BC15D8F3, got 2B90C7310BC7737D621539B01779987FCE199358C339DCECB77FFD33B2FC9BAC" module=consensus stack="goroutine 2881 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:727 +0x4c\npanic({0x1b3b3e0, 0xc0d298c880})\n\truntime/panic.go:838 +0x207\ngithub.com/tendermint/tendermint/consensus.(*State).enterPrecommit(0xc001264700, 0x432e87, 0x1)\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1408 +0x16ff\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0xc001264700, 0xc1025857c0, {0xc0c77da000, 0x28})\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:2123 +0x188f\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc001264700, 0xc1025857c0, {0xc0c77da000?, 0xc071230fc0?})\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1949 +0x2c\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc001264700, {{0x27da920?, 0xc020f600b8?}, {0xc0c77da000?, 0x0?}})\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:856 +0x44b\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc001264700, 0x0)\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:763 +0x419\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:379 +0x12d\n"
```

May18
```
May 18 14:50:50  2:50PM INF creating state snapshot height=4441500
May 18 15:31:30  3:31PM INF completed state snapshot format=1 height=4441500

May 18 17:16:41  5:16PM INF Starting epoch with identifier day epoch number 334 module=x/epochs
May 18 17:16:42  5:16PM INF Move delegation rewards to gauges
May 18 17:16:42  5:16PM ERR no delegation distribution info
May 18 17:16:43  message repeated 6 times: [ 5:16PM ERR no delegation distribution info]
May 18 17:16:43  5:16PM ERR no delegation distribution info
May 18 17:16:43  message repeated 3 times: [ 5:16PM ERR no delegation distribution info]
May 18 17:16:43  5:16PM ERR no delegation distribution info
May 18 17:16:43  message repeated 3 times: [ 5:16PM ERR no delegation distribution info]
May 18 17:16:43  5:16PM ERR no delegation distribution info
May 18 17:16:43  5:16PM ERR no delegation distribution info
May 18 17:16:43  5:16PM ERR no delegation distribution info
May 18 17:16:43  message repeated 9 times: [ 5:16PM ERR no delegation distribution info]
May 18 17:16:43  5:16PM ERR no delegation distribution info
May 18 17:16:43  message repeated 9 times: [ 5:16PM ERR no delegation distribution info]
May 18 17:16:43  5:16PM INF Distribute Superfluid gauges
May 18 17:20:17  5:20PM ERR Failed to reconnect to peer. Beginning exponential backoff addr={"id":"64d36f3a186a113c02db0cf7c588c7c85d946b5b","ip":"209.97.132.170","port":26656} elapsed=137019.589678 module=p2p
May 18 17:21:06  5:21PM INF Update all osmo equivalency multipliers
May 18 17:21:06  5:21PM INF Refresh all superfluid delegation amounts

May 18 17:22:49  5:22PM INF indexed block height=4442845 module=txindex

May 18 17:23:28  5:23PM INF indexed block height=4442860 module=txindex

May 18 17:23:33  5:23PM INF received proposal module=consensus proposal={"Type":32,"block_id":{"hash":"CCE37D2A2E94870CD35F0B08CE72B822C7C477505DDBB6393C0091D334FEE053","parts":{"hash":"7EE8128D82B1DCAB3EF8B527CD31390E0CE25C397F176219A0C2FA992E179243","total":4}},"height":4442861,"pol_round":-1,"round":0,"signature":"ncxiyNDvZVS5h112Xm4E9L7laNfyY2w5SUetOfhOVepDLJkqxF3JC0Ch9rL0Z78VS62PYN1b8B0ybYqMi6aLDA==","timestamp":"2022-05-18T17:23:32.967233704Z"}
May 18 17:23:33  5:23PM INF received complete proposal block hash=CCE37D2A2E94870CD35F0B08CE72B822C7C477505DDBB6393C0091D334FEE053 height=4442861 module=consensus
May 18 17:23:33  5:23PM ERR prevote step: ProposalBlock is invalid err="wrong Block.Header.AppHash.  Expected E3EB4F6879EEEEABA4889376EBA7A52908D08B7C2630B5624548D8039AFB70CC, got C0F67CEF763A00091BB201860EF71028A446B86C6C6FE4B852A518537F76D8C0" height=4442861 module=consensus round=0
May 18 17:23:34  5:23PM ERR CONSENSUS FAILURE!!! err="precommit step; +2/3 prevoted for an invalid block: wrong Block.Header.AppHash.  Expected E3EB4F6879EEEEABA4889376EBA7A52908D08B7C2630B5624548D8039AFB70CC, got C0F67CEF763A00091BB201860EF71028A446B86C6C6FE4B852A518537F76D8C0" module=consensus stack="goroutine 227286 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:727 +0x4c\npanic({0x1b3b3e0, 0xc02abed9f0})\n\truntime/panic.go:838 +0x207\ngithub.com/tendermint/tendermint/consensus.(*State).enterPrecommit(0xc000039c00, 0x43caed, 0x0)\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1408 +0x16ff\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0xc000039c00, 0xc0283515e0, {0xc22c35e690, 0x28})\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:2123 +0x188f\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc000039c00, 0xc0283515e0, {0xc22c35e690?, 0xc2c403b300?})\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1949 +0x2c\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc000039c00, {{0x27da920?, 0xc0a0553f60?}, {0xc22c35e690?, 0x0?}})\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:856 +0x44b\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc000039c00, 0x0)\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:763 +0x419\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:379 +0x12d\n"
May 18 17:23:36  5:23PM INF Timed out dur=3000 height=4442861 module=consensus round=0 step=3
```

May 22
```
May 22 16:25:35  4:25PM INF creating state snapshot height=4495500

May 22 17:01:55  5:01PM INF completed state snapshot format=1 height=4495500

May 22 17:16:40  5:16PM INF Starting epoch with identifier day epoch number 338 module=x/epochs

May 22 17:21:22  5:21PM INF executed block height=4495975 module=state num_invalid_txs=0 num_valid_txs=6
May 22 17:23:04  5:23PM INF indexed block height=4495975 module=txindex
...
...
May 22 17:30:52  5:30PM INF indexed block height=4496046 module=txindex
May 22 17:30:53  5:30PM INF Timed out dur=779.697625 height=4496047 module=consensus round=0 step=1
May 22 17:30:53  5:30PM INF commit is for a block we do not know about; set ProposalBlock=nil commit=65968EECD03AFEEE71751F0418E9DAE60FB59F3CF2DFC362624FD4FFCAC0EFAA commit_round=0 height=4496047 module=consensus proposal=
May 22 17:30:53  5:30PM INF received complete proposal block hash=65968EECD03AFEEE71751F0418E9DAE60FB59F3CF2DFC362624FD4FFCAC0EFAA height=4496047 module=consensus
May 22 17:30:53  5:30PM ERR CONSENSUS FAILURE!!! err="+2/3 committed an invalid block: wrong Block.Header.AppHash.  Expected AB20B0723811527BC0A9BCBDFE02A42B73A5519ACE1E3874B9B854D9090B341C, got D9E1004A529DFD6C87CC661899A10FC89C7129EF90044B6F4C2B1B3D823E30E5" module=consensus stack="goroutine 599332 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:727 +0x4c\npanic({0x1bdfda0, 0xc2c27258a0})\n\truntime/panic.go:838 +0x207\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc0073d8e00, 0x449aaf)\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1595 +0x1005\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc0073d8e00, 0x449aaf)\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1564 +0x305\ngithub.com/tendermint/tendermint/consensus.(*State).handleCompleteProposal(0xc0073d8e00, 0xf551?)\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1943 +0x36e\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc0073d8e00, {{0x27da860?, 0xc1b6da18f0?}, {0xc192fa41e0?, 0x0?}})\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:837 +0x1c5\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc0073d8e00, 0x0)\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:763 +0x419\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:379 +0x12d\n"
```

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by carameleon** [comment]
`wrong Block.Header.AppHash` has not happened since I added a kind of load balancing on our nodes for 10days.

**Comment by ValarDragon** [comment]
Oh awesome! Our plan for now was going to be to add a config option to enable/disable parallel queries, and have it default to off. And then let people turn it on, but take on risk of app hash failure for race conditions if they're under heavy load. (We currently view it that that feature had a lot of unsafe behavior that was never tested)

**Comment by p0mvn** [comment]
Going to close this for now since it's been stale for over a month. Please let us know if this issue is still a problem
