### ISSUE TITLE
Failing to start Osmosis with Docker. Panic: no base denom was set

### ISSUE THREAD

**Issue by dzmitrykliapkou** [osmosis-labs/osmosis#2548]
#### System information

Osmosis version: osmolabs/osmosis:11.0
OS & Version: Linux with Docker

#### Expected behaviour
Osmosis node is running

#### Actual behaviour
The container is failing to start with error `panic: no base denom was set`

#### Steps to reproduce the behaviour
```
mkdir -p config data wasm
wget -O config/genesis.json https://github.com/osmosis-labs/networks/raw/main/osmosis-1/genesis.json
chown -R 65532:65532 config data wasm
docker run -p 26657:26657 -p 26656:26656 -p 26658:26658 -p 9090:9090 -p 1317:1317 -v ./config:/osmosis/.osmosisd/config -v ./data:/osmosis/.osmosisd/data -v ./wasm:/osmosis/.osmosisd/wasm osmolabs/osmosis:11.0 start
```

#### Backtrace

````
osmosis-mainnet  | 9:21AM INF starting ABCI with Tendermint
osmosis-mainnet  | 9:21AM INF Starting multiAppConn service impl=multiAppConn module=proxy
osmosis-mainnet  | 9:21AM INF Starting localClient service connection=query impl=localClient module=abci-client
osmosis-mainnet  | 9:21AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
osmosis-mainnet  | 9:21AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
osmosis-mainnet  | 9:21AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
osmosis-mainnet  | 9:21AM INF Starting EventBus service impl=EventBus module=events
osmosis-mainnet  | 9:21AM INF Starting PubSub service impl=PubSub module=pubsub
osmosis-mainnet  | 9:21AM INF Starting IndexerService service impl=IndexerService module=txindex
osmosis-mainnet  | 9:21AM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=11.0.1
osmosis-mainnet  | 9:21AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
osmosis-mainnet  | 9:21AM INF initializing blockchain state from genesis.json
osmosis-mainnet  | 9:21AM INF running initialization for module module=capability
osmosis-mainnet  | 9:21AM INF running initialization for module module=auth
osmosis-mainnet  | 9:21AM INF running initialization for module module=bank
osmosis-mainnet  | 9:21AM INF running initialization for module module=distribution
osmosis-mainnet  | 9:21AM INF running initialization for module module=staking
osmosis-mainnet  | 9:21AM INF running initialization for module module=slashing
osmosis-mainnet  | 9:21AM INF running initialization for module module=gov
osmosis-mainnet  | 9:21AM INF running initialization for module module=mint
osmosis-mainnet  | 9:21AM INF minted coins from module account amount=225000000000000uosmo from=developer_vesting_unvested module=x/bank
osmosis-mainnet  | 9:21AM INF running initialization for module module=crisis
osmosis-mainnet  | 9:21AM INF running initialization for module module=ibc
osmosis-mainnet  | 9:21AM INF running initialization for module module=genutil
osmosis-mainnet  | panic: no base denom was set
osmosis-mainnet  |
osmosis-mainnet  | goroutine 1 [running]:
osmosis-mainnet  | github.com/cosmos/cosmos-sdk/x/genutil.DeliverGenTxs({{0x2ad5c78, 0xc000058030}, {0x2ae46a0, 0xc0000516c0}, {{0x0, 0x0}, {0xc00028c010, 0x9}, 0x0, {0x0, ...}, ...}, ...}, ...)
osmosis-mainnet  |      github.com/cosmos/cosmos-sdk@v0.46.0/x/genutil/gentx.go:113 +0x269
osmosis-mainnet  | github.com/cosmos/cosmos-sdk/x/genutil.InitGenesis(...)
osmosis-mainnet  |      github.com/cosmos/cosmos-sdk@v0.46.0/x/genutil/genesis.go:18
osmosis-mainnet  | github.com/cosmos/cosmos-sdk/x/genutil.AppModule.InitGenesis({{}, {_, _}, {_, _}, _, {_, _}}, {{0x2ad5c78, 0xc000058030}, ...}, ...)
osmosis-mainnet  |      github.com/cosmos/cosmos-sdk@v0.46.0/x/genutil/module.go:99 +0x13f
osmosis-mainnet  | github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x2ad5c78, 0xc000058030}, {0x2ae46a0, 0xc0000516c0}, {{0x0, 0x0}, {0xc00028c010, 0x9}, 0x0, ...}, ...}, ...)
osmosis-mainnet  |      github.com/cosmos/cosmos-sdk@v0.46.0/types/module/module.go:322 +0x429
osmosis-mainnet  | github.com/osmosis-labs/osmosis/v11/app.(*OsmosisApp).InitChainer(_, {{0x2ad5c78, 0xc000058030}, {0x2ae46a0, 0xc0000516c0}, {{0x0, 0x0}, {0xc00028c010, 0x9}, 0x0, ...}, ...}, ...)
osmosis-mainnet  |      github.com/osmosis-labs/osmosis/v11/app/app.go:338 +0x1b5
osmosis-mainnet  | github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc00023e780, {{0x0, 0xed85ec810, 0x0}, {0xc00028c010, 0x9}, 0xc0015244c0, {0x3c8d980, 0x0, 0x0}, ...})
osmosis-mainnet  |      github.com/cosmos/cosmos-sdk@v0.46.0/baseapp/abci.go:68 +0x535
osmosis-mainnet  | github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc0000afb60, {{0x0, 0xed85ec810, 0x0}, {0xc00028c010, 0x9}, 0xc0015244c0, {0x3c8d980, 0x0, 0x0}, ...})
osmosis-mainnet  |      github.com/tendermint/tendermint@v0.34.19/abci/client/local_client.go:272 +0x118
osmosis-mainnet  | github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x3?, {{0x0, 0xed85ec810, 0x0}, {0xc00028c010, 0x9}, 0xc0015244c0, {0x3c8d980, 0x0, 0x0}, ...})
osmosis-mainnet  |      github.com/tendermint/tendermint@v0.34.19/proxy/app_conn.go:77 +0x55
osmosis-mainnet  | github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x2487e33, 0x7}}, {0xc00028c010, 0x9}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
osmosis-mainnet  |      github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:319 +0xd78
osmosis-mainnet  | github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc00fbebb40, {0x2ae4df8, 0xc000302000})
osmosis-mainnet  |      github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:268 +0x3c8
osmosis-mainnet  | github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x2487e33, 0x7}}, {0xc00028c010, 0x9}, 0x1, 0x0, ...}, ...)
osmosis-mainnet  |      github.com/tendermint/tendermint@v0.34.19/node/node.go:325 +0x1b8
osmosis-mainnet  | github.com/tendermint/tendermint/node.NewNode(0xc0013e4280, {0x2ad2ab0, 0xc000239720}, 0xc0000915c0, {0x2ab98e0, 0xc00029bc08}, 0x1?, 0x0?, 0xc000091720, {0x2ad6f80, ...}, ...)
osmosis-mainnet  |      github.com/tendermint/tendermint@v0.34.19/node/node.go:733 +0x577
osmosis-mainnet  | github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x2aebb68, 0xc0013ad350}, {0x0, 0x0}, {0x2adac60, 0xc00123d5c0}, ...}, ...)
osmosis-mainnet  |      github.com/cosmos/cosmos-sdk@v0.46.0/server/start.go:262 +0x79b
osmosis-mainnet  | github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc00128db80?, {0xc001376e40?, 0x0?, 0x6?})
osmosis-mainnet  |      github.com/cosmos/cosmos-sdk@v0.46.0/server/start.go:129 +0x193
osmosis-mainnet  | github.com/spf13/cobra.(*Command).execute(0xc00128db80, {0xc001376d80, 0x6, 0x6})
osmosis-mainnet  |      github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
osmosis-mainnet  | github.com/spf13/cobra.(*Command).ExecuteC(0xc001242c80)
osmosis-mainnet  |      github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
osmosis-mainnet  | github.com/spf13/cobra.(*Command).Execute(...)
osmosis-mainnet  |      github.com/spf13/cobra@v1.4.0/command.go:902
osmosis-mainnet  | github.com/spf13/cobra.(*Command).ExecuteContext(...)
osmosis-mainnet  |      github.com/spf13/cobra@v1.4.0/command.go:895
osmosis-mainnet  | github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc001238498, 0x12})
osmosis-mainnet  |      github.com/cosmos/cosmos-sdk@v0.46.0/server/cmd/execute.go:36 +0x1eb
osmosis-mainnet  | main.main()
osmosis-mainnet  |      github.com/osmosis-labs/osmosis/v11/cmd/osmosisd/main.go:16 +0x31
osmosis-mainnet exited with code 2
````

**Comment by nicolaslara** [comment]
I think you have a typo on your data volume mount:

` ./data:/osmosis/.somosisd/data`

**Comment by dzmitrykliapkou** [comment]
Yep, accidentally made one, but it is only in this issue description

**Comment by p0mvn** [comment]
Is there a chance that you are trying to run the v1 genesis on v11 without having the state updated to v11?

When I run `cat genesis.json | jq '.app_state|keys'` I don't see the `txfees` module. This is the module that is returning `panic: no base denom was set`.

I believe that this module was introduced post-genesis. So my guess is that the v11 osmosis initializes the v1 genesis and ends up not having the `txfees` state.

Depending on what you are trying to do, you can:
- sync from genesis by using v1 (version that does not have the txfees module) and swapping binaries at the right heights
- use v11 but sync your node's state accordingly

We have an installer that can configure either option: https://get.osmosis.zone/

However, that would not use Docker. If using Docker is the goal, I  you can try getting a quicksync snapshot to mount on the `data` folder. Similar to how `config` and other folders were mounted. This is where quicksync snapshots can be found: https://quicksync.io/networks/osmosis.html

Please let me know if that helps

**Comment by dzmitrykliapkou** [comment]
Hmm, ok, I'll try. Downloading the archive snapshot on another node right now

**Comment by czarcas7ic** [comment]
@dzmitrykliapkou what is it you are trying to accomplish? You likely wont need an archive snapshot (and if you do, idk if docker would be the way to go)

**Comment by p0mvn** [comment]
Hi @dzmitrykliapkou . Is there still anything that we can help with? If not, I will close this issue

**Comment by dzmitrykliapkou** [comment]
> @dzmitrykliapkou what is it you are trying to accomplish? You likely wont need an archive snapshot (and if you do, idk if docker would be the way to go)

We definitely need archive ones, that is for an application. We are running Cosmos archive nodes using docker, so I hope there will be no issues with Osmosis

**Comment by dzmitrykliapkou** [comment]
> Hi @dzmitrykliapkou . Is there still anything that we can help with? If not, I will close this issue

Think the issue can be closed
