### ISSUE TITLE
Error reconnecting to peer

### ISSUE THREAD

**Issue by dbarobin** [osmosis-labs/osmosis#3036]
#### System information

Osmosis version: `12.2.0`
OS & Version: Ubuntu 22.04 LTS, arm64
Commit hash: ab00b76f792f051d69c700e7c6563ad27563e3a8

#### Expected behavior

Node syncs to the latest block.

#### Actual behaviour

Node synchronization is suspended, and the block height does not change.

#### Steps to reproduce the behavior

Refer: https://docs.osmosis.zone/networks/join-mainnet/

``` bash
# create a full node
$ curl -sL https://get.osmosis.zone/install > i.py && python3 i.py

# update peers, refer https://github.com/osmosis-labs/osmosis/blob/main/networks/peers.md
$ vim config/config.toml

persistent_peers = "8f67a2fcdd7ade970b1983bf1697111d35dfdd6f@52.79.199.137:26656,00c328a33578466c711874ec5ee7ada75951f99a@35.82.201.64:26656,cfb6f2d686014135d4a6034aa6645abd0020cac6@52.79.88.57:26656,8d9967d5f865c68f6fe2630c0f725b0363554e77@134.255.252.173:26656,785bc83577e3980545bac051de8f57a9fd82695f@194.233.164.146:26656,778fdedf6effe996f039f22901a3360bc838b52e@161.97.187.189:36657,64d36f3a186a113c02db0cf7c588c7c85d946b5b@209.97.132.170:26656,4d9ac3510d9f5cfc975a28eb2a7b8da866f7bc47@37.187.38.191:26656,2115945f074ddb038de5d835e287fa03e32f0628@95.217.43.85:26656,bf2c480eff178d2647ba1adfeee8ced568fe752c@91.65.128.44:26656,2f9c16151400d8516b0f58c030b3595be20b804c@37.120.245.167:26656,bada684070727cb3dda430bcc79b329e93399665@173.212.240.91:26656,83adaa38d1c15450056050fd4c9763fcc7e02e2c@ec2-44-234-84-104.us-west-2.compute.amazonaws.com:26656,23142ab5d94ad7fa3433a889dcd3c6bb6d5f247d@95.217.193.163:26656,f82d1a360dc92d4e74fdc2c8e32f4239e59aebdf@95.217.121.243:26656,e437756a853061cc6f1639c2ac997d9f7e84be67@144.76.183.180:26656,3fea02d121cb24503d5fbc53216a527257a9ab55@143.198.145.208:26656,7de029fa5e9c1f39557c0e3523c1ae0b07c58be0@78.141.219.223:26656,7024d1ca024d5e33e7dc1dcb5ed08349768220b9@134.122.42.20:26656,d326ad6dffa7763853982f334022944259b4e7f4@143.110.212.33:26656,e7916387e05acd53d1b8c0f842c13def365c7bb6@176.9.64.212:26666,55eea69c21b46000c1594d8b4a448563b075d9e3@34.107.19.235:26656,9faf468b90a3b2b85ffd88645a15b3715f68bb0b@195.201.122.100:26656,ffc82412c0261a94df122b9cc0ce1de81da5246b@15.222.240.16:26656,5b90a530464885fd28c31f698c81694d0b4a1982@35.183.238.70:26656,7b6689cb18d625bbc069aa99d9d5521293db442c@51.158.97.192:26656,fda06dcebe2acd17857a6c9e9a7b365da3771ceb@52.206.252.176:26656,8d9fd90a009e4b6e9572bf9a84b532a366790a1d@193.26.156.221:26656"

# keep udp:26656 firewall open

# update osmosisd to latest release
$ wget https://github.com/osmosis-labs/osmosis/releases/download/v12.2.0/osmosisd-12.2.0-linux-arm64
$ mv osmosisd-12.2.0-linux-arm64 osmosisd
$ \cp osmosisd /home/ubuntu/.osmosisd/cosmovisor/current/bin/osmosisd

# restart cosmovisor
$ sudo systemctl restart cosmovisor

# check catching_up
$ osmosisd status 2>&1 | jq "{catching_up: .SyncInfo.catching_up}"
{
  "catching_up": true
}

# check latest_block_height, it keeps the same
$ osmosisd status 2>&1 | jq "{latest_block_height: .SyncInfo.latest_block_height}"
{
  "latest_block_height": "6477589"
}
$ osmosisd status 2>&1 | jq "{latest_block_height: .SyncInfo.latest_block_height}"
{
  "latest_block_height": "6477589"
}

```

#### Backtrace

````
$ journalctl -u cosmovisor -f

Oct 18 01:10:59 osmosis-mainnet cosmovisor[444519]: 1:10AM INF service stop impl={"Logger":{}} module=p2p msg={} peer={"id":"63e4dd6530bf4dc4c2202be256b262a27d661106","ip":"157.90.5.101","port":26656}
Oct 18 01:10:59 osmosis-mainnet cosmovisor[444519]: 1:10AM ERR Stopping peer for error err="read tcp 172.31.0.132:44698->157.90.5.101:26656: use of closed network connection" module=p2p peer={"Data":{},"Logger":{}}
Oct 18 01:10:59 osmosis-mainnet cosmovisor[444519]: 1:10AM INF service stop impl={"Data":{},"Logger":{}} module=p2p msg={} peer={"id":"63e4dd6530bf4dc4c2202be256b262a27d661106","ip":"157.90.5.101","port":26656}
Oct 18 01:10:59 osmosis-mainnet cosmovisor[444519]: 1:10AM ERR error while stopping peer error="already stopped" module=p2p
Oct 18 01:11:03 osmosis-mainnet cosmovisor[444519]: 1:11AM ERR Error in validation err="wrong Block.Header.AppHash.  Expected 8D964BBAC76228274E94F9317037CFAAAF2533375CE862E17D63E53A11E82979, got FF8297DFE414056FBF0E19760DA5609DA955B20EA7A4E206CDC28D12935442FA" module=blockchain
Oct 18 01:11:03 osmosis-mainnet cosmovisor[444519]: 1:11AM ERR Stopping peer for error err="blockchainReactor validation error: wrong Block.Header.AppHash.  Expected 8D964BBAC76228274E94F9317037CFAAAF2533375CE862E17D63E53A11E82979, got FF8297DFE414056FBF0E19760DA5609DA955B20EA7A4E206CDC28D12935442FA" module=p2p peer={"Data":{},"Logger":{}}
Oct 18 01:11:03 osmosis-mainnet cosmovisor[444519]: 1:11AM INF service stop impl={"Logger":{}} module=p2p msg={} peer={"id":"baa7572065e18f1796f50b336a01dcaa85eccd01","ip":"65.108.101.214","port":26656}
Oct 18 01:11:03 osmosis-mainnet cosmovisor[444519]: 1:11AM ERR Stopping peer for error err="read tcp 172.31.0.132:59322->65.108.101.214:26656: use of closed network connection" module=p2p peer={"Data":{},"Logger":{}}
Oct 18 01:11:03 osmosis-mainnet cosmovisor[444519]: 1:11AM ERR error while stopping peer error="already stopped" module=p2p
Oct 18 01:11:03 osmosis-mainnet cosmovisor[444519]: 1:11AM INF service stop impl={"Data":{},"Logger":{}} module=p2p msg={} peer={"id":"baa7572065e18f1796f50b336a01dcaa85eccd01","ip":"65.108.101.214","port":26656}
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=2 numToDial=38
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"63d7f97e4c9149dc33cc925f26a81af24b7c1a99","ip":"35.204.138.97","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"f515a8599b40f0e84dfad935ba414674ab11a668","ip":"35.181.0.85","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"18bd71b972a98946995707dcb3def35a0711509d","ip":"80.71.57.75","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"6356bf6b58b3a8c2015d411b453e1521e511eafd","ip":"65.108.242.218","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"11de40c9740e652c7b1993a142a7dee62ffdccb5","ip":"18.117.183.121","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"94a5f37693ba36617029a47d654460d161678af6","ip":"34.89.142.244","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"fd651cfe771597c7fe930936bff077ce42d636a3","ip":"51.161.84.86","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"64d36f3a186a113c02db0cf7c588c7c85d946b5b","ip":"209.97.132.170","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"fa8fec441188da859587d39445f4ea9f5b0c540a","ip":"74.118.140.24","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"ec33a5bb7ea7f0a9532e8745441b9c80f78b980a","ip":"46.101.181.7","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"ac3af6cafef09b66e8dc6d97453476b365a1fa48","ip":"135.125.104.217","port":34656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"d32937705359da13feb29b4348957d4fbfe44f7b","ip":"43.153.15.2","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"b4792d3c344e336b0f811dd8079dcdfce45fb24f","ip":"147.182.213.34","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"97e4468ac589eac505a800411c635b14511a61bb","ip":"5.9.209.56","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"f537b32b2aea38eec731ef97d8d835207652bd27","ip":"54.201.94.65","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"44c682a034767f41086816337c92e0e447793724","ip":"104.196.19.158","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"405bc3ff9f9490750cadf8a53e47cd9484d3f409","ip":"52.25.123.11","port":30067} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"87908aadba9cf7b95bb7d0680df4be1c954a8ddb","ip":"35.91.34.51","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"c38d8d4cf2768bb9cbf6c835aa93328e9ad64bd8","ip":"18.117.94.111","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"30eabf71ba133d987e84668e10eef45b6f810710","ip":"135.181.133.159","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"6fc23ee451a5969853825d861532676b84d7bf0c","ip":"161.97.72.137","port":26716} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"43d480c9493cfb039031323faccee1f83b4b82c0","ip":"95.217.244.43","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"2c4fdab7411a9b219e5a8f617bc0130e11f1099b","ip":"18.189.143.65","port":46656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"ccf64797d50b8df036d19b99edcfdfb28242c66a","ip":"44.192.9.95","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"76c3cfb338a4fe3e90939e0b0bef0260056962bf","ip":"3.122.114.254","port":29656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"9219cc2dadbdd680ccbfc7b842bb2432281e5636","ip":"3.69.197.100","port":29656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"3b4e9cfbc1ab7d66a3f81c22470a5681ddac70b9","ip":"65.108.71.119","port":36656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"147d0fe101bbd9e200ccbe3d353d5e7762cb02ee","ip":"207.154.201.8","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"d8e62cfb46f06e68ef6dc2984af8a4afc1f34fd2","ip":"8.9.36.180","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"ff4030fa2c73e5c852581f4d619c278d95f9f269","ip":"34.247.193.125","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"a4e6384d4ae6c0d8f0595e7425c81239417f0879","ip":"54.75.223.189","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"747d01891a83d6f759d88f9be07159c268b584b0","ip":"141.95.65.98","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"a9da2e2625b73be360596abf0aa4d4c5e77e81a4","ip":"154.53.41.12","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"7f3b9696d7b7b39a599e9a786287410eccb39085","ip":"37.61.213.215","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"1e027253c8e3b6dae8dc9ecf12854f579b3869f0","ip":"170.75.251.230","port":25565} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"f4f3d31b8e144a4d86e13fcb84b17b574c737bf4","ip":"34.91.30.41","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"88446c2a6bf8a460e465da1f89fe0462521c7dfb","ip":"65.21.141.119","port":26656} module=p2p
Oct 18 01:11:21 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Dialing peer address={"id":"02ba17bf964a55d37f6a910d59cf1db399d71e09","ip":"2a01:4f9:3b:5398::2","port":26656} module=p2p
Oct 18 01:11:22 osmosis-mainnet cosmovisor[444519]: 1:11AM INF service start impl="Peer{MConn{18.189.143.65:46656} 2c4fdab7411a9b219e5a8f617bc0130e11f1099b out}" module=p2p msg={} peer={"id":"2c4fdab7411a9b219e5a8f617bc0130e11f1099b","ip":"18.189.143.65","port":46656}
Oct 18 01:11:22 osmosis-mainnet cosmovisor[444519]: 1:11AM INF service start impl=MConn{18.189.143.65:46656} module=p2p msg={} peer={"id":"2c4fdab7411a9b219e5a8f617bc0130e11f1099b","ip":"18.189.143.65","port":46656}
Oct 18 01:11:22 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Added peer module=p2p peer={"Data":{},"Logger":{}}
Oct 18 01:11:22 osmosis-mainnet cosmovisor[444519]: 1:11AM INF service start impl="Peer{MConn{65.108.242.218:26656} 6356bf6b58b3a8c2015d411b453e1521e511eafd out}" module=p2p msg={} peer={"id":"6356bf6b58b3a8c2015d411b453e1521e511eafd","ip":"65.108.242.218","port":26656}
Oct 18 01:11:22 osmosis-mainnet cosmovisor[444519]: 1:11AM INF service start impl=MConn{65.108.242.218:26656} module=p2p msg={} peer={"id":"6356bf6b58b3a8c2015d411b453e1521e511eafd","ip":"65.108.242.218","port":26656}
Oct 18 01:11:22 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Added peer module=p2p peer={"Data":{},"Logger":{}}
Oct 18 01:11:22 osmosis-mainnet cosmovisor[444519]: 1:11AM INF Connection is closed @ recvRoutine (likely by the other side) conn={"Logger":{}} module=p2p peer={"id":"6356bf6b58b3a8c2015d411b453e1521e511eafd","ip":"65.108.242.218","port":26656}
Oct 18 01:11:22 osmosis-mainnet cosmovisor[444519]: 1:11AM INF service stop impl={"Logger":{}} module=p2p msg={} peer={"id":"6356bf6b58b3a8c2015d411b453e1521e511eafd","ip":"65.108.242.218","port":26656}
Oct 18 01:11:22 osmosis-mainnet cosmovisor[444519]: 1:11AM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{}}
Oct 18 01:11:22 osmosis-mainnet cosmovisor[444519]: 1:11AM INF service stop impl={"Data":{},"Logger":{}} module=p2p msg={} peer={"id":"6356bf6b58b3a8c2015d411b453e1521e511eafd","ip":"65.108.242.218","port":26656}
````

**Comment by czarcas7ic** [comment]
Can you please remove your .osmosisd directory and try running this again? Also use the new script at https://get.osmosis.zone, you posted the old one

**Comment by dbarobin** [comment]
> Can you please remove your .osmosisd directory and try running this again? Also use the new script at https://get.osmosis.zone, you posted the old one

I rebuilt my full node using this script, but after a few minutes of syncing, the sync stopped. The following log appeared.

````
Oct 19 06:39:35 osmosis-mainnet cosmovisor[452831]: 6:39AM INF Dialing peer address={"id":"362b1fbed7d54f9c1d451db9afe5c1a29e255411","ip":"18.190.50.153","port":26656} module=p2p
Oct 19 06:39:35 osmosis-mainnet cosmovisor[452831]: 6:39AM INF Dialing peer address={"id":"4935c7145ec8a5f34377fcc5e12611a32ceced00","ip":"34.220.182.212","port":26656} module=p2p
Oct 19 06:39:35 osmosis-mainnet cosmovisor[452831]: 6:39AM INF Dialing peer address={"id":"52a1cc68eb86ff65722cc9dd01476627b76a8a17","ip":"52.39.95.201","port":32083} module=p2p
Oct 19 06:39:35 osmosis-mainnet cosmovisor[452831]: 6:39AM INF Dialing peer address={"id":"3be395dfcf3211fad403eb2799dac2dcc5da5082","ip":"176.57.189.209","port":26716} module=p2p
Oct 19 06:39:35 osmosis-mainnet cosmovisor[452831]: 6:39AM INF Dialing peer address={"id":"f954be47b44e6bc548a755cd674bacc1ce320960","ip":"34.73.25.140","port":26656} module=p2p
Oct 19 06:39:35 osmosis-mainnet cosmovisor[452831]: 6:39AM INF Dialing peer address={"id":"b7e3e32ae9bb06e958ba15f1de7dccc43603fe01","ip":"18.192.48.164","port":29656} module=p2p
Oct 19 06:39:35 osmosis-mainnet cosmovisor[452831]: 6:39AM INF Dialing peer address={"id":"a3c81dd3bef3b8d81b9aa11dd299e528a67ac1eb","ip":"143.198.100.193","port":26656} module=p2p
Oct 19 06:39:35 osmosis-mainnet cosmovisor[452831]: 6:39AM INF Dialing peer address={"id":"f9309f44ad0c3382f92854eb5bf5c35d58e8883b","ip":"35.238.25.67","port":26656} module=p2p
Oct 19 06:39:35 osmosis-mainnet cosmovisor[452831]: 6:39AM INF Dialing peer address={"id":"f295bb106d5f8d8e5e2893e490848ca3414ab354","ip":"44.242.137.240","port":32013} module=p2p
Oct 19 06:39:35 osmosis-mainnet cosmovisor[452831]: 6:39AM INF Dialing peer address={"id":"669fb1508acfb2b52090d3d7bd1832f4885a5688","ip":"74.118.140.25","port":26656} module=p2p
Oct 19 06:39:35 osmosis-mainnet cosmovisor[452831]: 6:39AM INF Dialing peer address={"id":"d880c6b420d301837fcef443e687ac05859e7fe7","ip":"51.210.154.28","port":34656} module=p2p
Oct 19 06:39:35 osmosis-mainnet cosmovisor[452831]: 6:39AM INF Dialing peer address={"id":"c236133c94ca5d3e01e76482730fc6dd6d5e87a8","ip":"3.67.177.84","port":29656} module=p2p
Oct 19 06:39:35 osmosis-mainnet cosmovisor[452831]: 6:39AM INF Dialing peer address={"id":"334690d9cde926ca425d91aa37c64544249e8c8a","ip":"167.172.43.173","port":26656} module=p2p
Oct 19 06:39:35 osmosis-mainnet cosmovisor[452831]: 6:39AM INF Dialing peer address={"id":"df65b335f668b9feae5f8807ec899f96acd15d79","ip":"165.227.138.32","port":26656} module=p2p
Oct 19 06:39:35 osmosis-mainnet cosmovisor[452831]: 6:39AM INF Dialing peer address={"id":"bc0eeeabdc558cdb39f4a8148b5022ba537512b4","ip":"46.166.138.217","port":26656} module=p2p
Oct 19 06:39:35 osmosis-mainnet cosmovisor[452831]: 6:39AM INF Dialing peer address={"id":"51ec9876b284f7d468586a3b5784e7fc1350bb7d","ip":"99.81.77.238","port":26656} module=p2p
Oct 19 06:39:35 osmosis-mainnet cosmovisor[452831]: 6:39AM INF Dialing peer address={"id":"deaa212c5c4eeed0c7580989f4b3e27fcbebaf5b","ip":"51.222.105.179","port":26656} module=p2p
Oct 19 06:39:35 osmosis-mainnet cosmovisor[452831]: 6:39AM INF Dialing peer address={"id":"1cb460a03b478e149c03b2888c8425916d681318","ip":"159.223.36.236","port":26656} module=p2p
Oct 19 06:39:35 osmosis-mainnet cosmovisor[452831]: 6:39AM INF Dialing peer address={"id":"f54876e27453887a448c380c69d9011a48cfffe9","ip":"172.104.195.9","port":26596} module=p2p
Oct 19 06:39:35 osmosis-mainnet cosmovisor[452831]: 6:39AM INF Dialing peer address={"id":"8ecc0d653a4bba4a8daa136760170a1395ba74cf","ip":"68.183.219.89","port":26656} module=p2p
````

**Comment by czarcas7ic** [comment]
Hmm, I just changed the installer to use a difference version. If you would like to retry again and lmk that would be great.

**Comment by dbarobin** [comment]
Still doesn't work, block height stopped at 6506661.

````
Oct 20 02:11:02 osmosis-mainnet cosmovisor[462743]: 2:11AM INF Added peer module=p2p peer={"Data":{},"Logger":{}}
Oct 20 02:11:02 osmosis-mainnet cosmovisor[462743]: 2:11AM INF Connection is closed @ recvRoutine (likely by the other side) conn={"Logger":{}} module=p2p peer={"id":"b022cf434d838b0bc6135bfe45fb083c270233ce","ip":"65.21.204.171","port":36656}
Oct 20 02:11:02 osmosis-mainnet cosmovisor[462743]: 2:11AM INF service stop impl={"Logger":{}} module=p2p msg={} peer={"id":"b022cf434d838b0bc6135bfe45fb083c270233ce","ip":"65.21.204.171","port":36656}
Oct 20 02:11:02 osmosis-mainnet cosmovisor[462743]: 2:11AM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{}}
Oct 20 02:11:02 osmosis-mainnet cosmovisor[462743]: 2:11AM INF service stop impl={"Data":{},"Logger":{}} module=p2p msg={} peer={"id":"b022cf434d838b0bc6135bfe45fb083c270233ce","ip":"65.21.204.171","port":36656}
Oct 20 02:11:02 osmosis-mainnet cosmovisor[462743]: 2:11AM INF commit is for a block we do not know about; set ProposalBlock=nil commit=C83C52B5012426014AB5F600494FB8CA4EBE6716C443AAC884B5C30551C1E43D commit_round=0 height=6506662 module=consensus proposal={}
Oct 20 02:11:02 osmosis-mainnet cosmovisor[462743]: 2:11AM INF received complete proposal block hash=C83C52B5012426014AB5F600494FB8CA4EBE6716C443AAC884B5C30551C1E43D height=6506662 module=consensus
Oct 20 02:11:02 osmosis-mainnet cosmovisor[462743]: 2:11AM ERR CONSENSUS FAILURE!!! err="+2/3 committed an invalid block: wrong Block.Header.AppHash.  Expected E6AC820E225AEB081A67E967D44D7C7F526CE968A9937652A3CAD5909A041D96, got D9B56AD37646EE900EA18C47892CBE812EB8D434216A660E8079581DA6BC0169" module=consensus stack="goroutine 36559 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x68\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()\n\tgithub.com/tendermint/tendermint@v0.34.21/consensus/state.go:727 +0x48\npanic({0x1acd1e0, 0x4045cdd620})\n\truntime/panic.go:838 +0x20c\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0x40013f8a80, 0x6348a6)\n\tgithub.com/tendermint/tendermint@v0.34.21/consensus/state.go:1599 +0xe84\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0x40013f8a80, 0x6348a6)\n\tgithub.com/tendermint/tendermint@v0.34.21/consensus/state.go:1568 +0x294\ngithub.com/tendermint/tendermint/consensus.(*State).handleCompleteProposal(0x40013f8a80, 0x432c?)\n\tgithub.com/tendermint/tendermint@v0.34.21/consensus/state.go:1947 +0x32c\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0x40013f8a80, {{0x238f860?, 0x4039b3f2c0?}, {0x403bf403f0?, 0x0?}})\n\tgithub.com/tendermint/tendermint@v0.34.21/consensus/state.go:837 +0x150\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0x40013f8a80, 0x0)\n\tgithub.com/tendermint/tendermint@v0.34.21/consensus/state.go:763 +0x2e0\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\tgithub.com/tendermint/tendermint@v0.34.21/consensus/state.go:379 +0xf4\n"
Oct 20 02:11:02 osmosis-mainnet cosmovisor[462743]: 2:11AM INF service stop impl={"Logger":{}} module=consensus msg={} wal=/home/ubuntu/.osmosisd/data/cs.wal/wal
Oct 20 02:11:02 osmosis-mainnet cosmovisor[462743]: 2:11AM INF service stop impl={"Dir":"/home/ubuntu/.osmosisd/data/cs.wal","Head":{"ID":"cVG9GQ62dwrK:/home/ubuntu/.osmosisd/data/cs.wal/wal","Path":"/home/ubuntu/.osmosisd/data/cs.wal/wal"},"ID":"group:cVG9GQ62dwrK:/home/ubuntu/.osmosisd/data/cs.wal/wal","Logger":{}} module=consensus msg={} wal=/home/ubuntu/.osmosisd/data/cs.wal/wal
Oct 20 02:11:31 osmosis-mainnet cosmovisor[462743]: 2:11AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=3 numToDial=37
Oct 20 02:11:31 osmosis-mainnet cosmovisor[462743]: 2:11AM INF Dialing peer address={"id":"9dce7fb95763e9216d85ce062eaee39e2c47c810","ip":"18.237.84.228","port":31643} module=p2p
Oct 20 02:11:31 osmosis-mainnet cosmovisor[462743]: 2:11AM INF Dialing peer address={"id":"038a395d13b53398ee75017056ee1713aa3f7cd8","ip":"3.249.22.171","port":26656} module=p2p
Oct 20 02:11:31 osmosis-mainnet cosmovisor[462743]: 2:11AM INF Dialing peer address={"id":"686d3abb2513d0ab35b8efc5a597d740f199e186","ip":"167.99.223.156","port":26656} module=p2p
Oct 20 02:11:31 osmosis-mainnet cosmovisor[462743]: 2:11AM INF Dialing peer address={"id":"457164de65c1c01f32ec2a4a4738709362ac9a3d","ip":"134.122.35.19","port":26656} module=p2p
Oct 20 02:11:31 osmosis-mainnet cosmovisor[462743]: 2:11AM INF Dialing peer address={"id":"a095b01fd1e6d6eb68371ad2e7d996e5740aa480","ip":"167.114.174.5","port":26656} module=p2p
Oct 20 02:11:31 osmosis-mainnet cosmovisor[462743]: 2:11AM INF Dialing peer address={"id":"8291f5a2fca65e9c7f21b97ae361e1777c8ff93e","ip":"51.91.74.235","port":26656} module=p2p
Oct 20 02:11:31 osmosis-mainnet cosmovisor[462743]: 2:11AM INF Dialing peer address={"id":"d6228417e917647022d7a6ae2cca8692645801a9","ip":"18.119.165.78","port":26656} module=p2p
Oct 20 02:11:31 osmosis-mainnet cosmovisor[462743]: 2:11AM INF Dialing peer address={"id":"9abc1080bf67b96903b8087379b083ebe52c9b83","ip":"35.235.89.254","port":26656} module=p2p
Oct 20 02:11:31 osmosis-mainnet cosmovisor[462743]: 2:11AM INF Dialing peer address={"id":"385bfadf8d9e09fb6bf0602e775eb1b27fa64272","ip":"3.86.46.95","port":26656} module=p2p
Oct 20 02:11:31 osmosis-mainnet cosmovisor[462743]: 2:11AM INF Dialing peer address={"id":"52a1cc68eb86ff65722cc9dd01476627b76a8a17","ip":"52.39.95.201","port":32083} module=p2p
Oct 20 02:11:31 osmosis-mainnet cosmovisor[462743]: 2:11AM INF Dialing peer address={"id":"c8408fd524ff2c38e44b8e387ca0e7183092431e","ip":"18.197.142.143","port":29656} module=p2p
````

**Comment by dbarobin** [comment]
After replacing the node server with an x86/64 architecture server, the complete synchronization is working. It seems that Osmosis is not very compatible with ARM servers.

**Comment by shawnhcd** [comment]
> After replacing the node server with an x86/64 architecture server, the complete synchronization is working. It seems that Osmosis is not very compatible with ARM servers.

Hello, I have the same problem as you, used x86/64 architecture according to your method and still does not work. Is there any other solution?
