### ISSUE TITLE
AppHash wrong on block 1

### ISSUE THREAD

**Issue by hydrogen18** [osmosis-labs/osmosis#343]
Steps:

1. Download v1.0.1 tarball
2. Decompress
3. Compile from source with golang v1.16.5 on amd64 machine
4. Setup all peers from 'peers.md'  in osmosis network as seeds in the config files
5. Get the genesis from osmosis network repo and copy into your config directory (MD5: 2f0905bf3976bcf0a56bb91c0147c4bf)
6. Startup the node
7. Wait for it to process the genesis
8. Wait for it to dial peers

**Expected:** At some point the node should be able to talk to enough peers to start getting caught up

**Actual:** The node eventually connects but gets the wrong appHash on block 1

Log shows this
```
Jun 23 11:08:34 s181112 osmosisd[24626]: 11:08AM INF executed block height=1 module=state num_invalid_txs=0 num_valid_txs=0
Jun 23 11:08:43 s181112 osmosisd[24626]: 11:08AM INF commit synced commit=436F6D6D697449447B5B32352031333920382032323920313638203536203131362031343020323234203338203220343120313038203232312034302034322032312031333320312031333720363320393920313234203837203133322032353520323033203134312031312032343820313339203132395D3A317D
Jun 23 11:08:43 s181112 osmosisd[24626]: 11:08AM INF committed state app_hash=198B08E5A838748CE02602296CDD282A158501893F637C5784FFCB8D0BF88B81 height=1 module=state num_txs=0
Jun 23 11:08:43 s181112 osmosisd[24626]: 11:08AM INF indexed block height=1 module=txindex
Jun 23 11:08:43 s181112 osmosisd[24626]: panic: Failed to process committed block (2:5796003F36683587414480457DC674395F9DCB76F5C87173F5C103B5FD238CEC): wrong Block.Header.AppHash.  Expected 198B08E5A838748CE02602296CDD282A158501893F637C5784FFCB8D0BF88B81, got 4631EFE2D18E4AB6B18522A05A839CABC8B1BB8E5A7CBE413DB69D39104CEB3A
Jun 23 11:08:43 s181112 osmosisd[24626]: goroutine 175123 [running]:
Jun 23 11:08:43 s181112 osmosisd[24626]: github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000e02c40, 0x0)
Jun 23 11:08:43 s181112 osmosisd[24626]:         github.com/tendermint/tendermint@v0.34.10/blockchain/v0/reactor.go:401 +0x15bf
Jun 23 11:08:43 s181112 osmosisd[24626]: created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
Jun 23 11:08:43 s181112 osmosisd[24626]:         github.com/tendermint/tendermint@v0.34.10/blockchain/v0/reactor.go:110 +0x8c
Jun 23 11:08:43 s181112 systemd[1]: osmosis-node.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

some other information

1. I ran a hard drive self test on the node that is having this issue just to be sure, it passed
2. it doesn't have any other problems
3. It's a bare metal machine running an older AMD cpu (see below)
4.  It doesn't have ECC memory, is it possible this is caused by that?

from /proc/cpuinfo
```
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 16
model		: 10
model name	: AMD Phenom(tm) II X6 1045T Processor
stepping	: 0
microcode	: 0x10000dc
cpu MHz		: 803.566
cache size	: 512 KB
physical id	: 0
siblings	: 6
core id		: 0
cpu cores	: 6
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 6
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt cpb hw_pstate vmmcall npt lbrv svm_lock nrip_save pausefilter
```

**Comment by ValarDragon** [comment]
Hrmm, I'm rather confused by this. Just to sanity check, can you print out the `osmosisd version`

My full node is running with the same genesis hash as yours, and 
```
osmosisd version
1.0.1-1-ga6c29cb
```

**Comment by hydrogen18** [comment]
When I run the version command this is what I get 

```
$ osmosisd version

```
It's just a blank line. I compiled from the source release.

**Comment by ValarDragon** [comment]
can you paste the latest commit hash from `git log`?

**Comment by hydrogen18** [comment]
I did not use git, I downloaded this release:

https://github.com/osmosis-labs/osmosis/releases/tag/v1.0.1

**Comment by ValarDragon** [comment]
Could you try getting the repo via git?
