### ISSUE TITLE
Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain

### ISSUE THREAD

**Issue by atomlab** [osmosis-labs/osmosis#3521]
#### System information

Osmosis version: `12.3.0`
OS & Version: Linux (debian 11.2)

#### Expected behaviour
node is up and running

#### Actual behaviour

Crashed with an error
```
Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain
```

#### Steps to reproduce the behaviour

```
# Run docker container 
docker run --rm -it debian:11.2 bash

# Download osmosisd
apt update && apt install -y wget 
wget https://github.com/osmosis-labs/osmosis/releases/download/v12.3.0/osmosisd-12.3.0-linux-amd64 -O /usr/bin/osmosisd
chmod +x /usr/bin/osmosisd

# Configure 
osmosisd init --chain-id=osmosis-1 moniker --home /
wget -O /config/genesis.json https://github.com/osmosis-labs/networks/raw/main/osmosis-1/genesis.json

#  Start
osmosisd start --home /

```

#### Backtrace

````
5:05PM INF starting ABCI with Tendermint
5:05PM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false store_key="KVStoreKey{0xc0005849f0, superfluid}" version=0
5:05PM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false store_key="KVStoreKey{0xc0005849a0, incentives}" version=0
5:05PM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false store_key="KVStoreKey{0xc000584950, transfer}" version=0
5:05PM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false store_key="KVStoreKey{0xc0005848c0, mint}" version=0
5:05PM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false store_key="KVStoreKey{0xc000584a00, wasm}" version=0
5:05PM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false store_key="KVStoreKey{0xc000584920, icahost}" version=0
5:05PM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false store_key="KVStoreKey{0xc000584970, gamm}" version=0
5:05PM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false store_key="KVStoreKey{0xc0005848d0, distribution}" version=0
5:05PM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false store_key="KVStoreKey{0xc0005848f0, gov}" version=0
5:05PM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false store_key="KVStoreKey{0xc000584890, acc}" version=0
5:05PM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false store_key="KVStoreKey{0xc000584910, ibc}" version=0
5:05PM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false store_key="KVStoreKey{0xc0005849c0, poolincentives}" version=0
5:05PM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false store_key="KVStoreKey{0xc0005849b0, epochs}" version=0
5:05PM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false store_key="KVStoreKey{0xc0005848a0, bank}" version=0
5:05PM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false store_key="KVStoreKey{0xc0005848b0, staking}" version=0
5:05PM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false store_key="KVStoreKey{0xc000584990, lockup}" version=0
5:05PM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false store_key="KVStoreKey{0xc000584900, params}" version=0
5:05PM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false store_key="KVStoreKey{0xc000584980, twap}" version=0
5:05PM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false store_key="KVStoreKey{0xc000584a10, tokenfactory}" version=0
5:05PM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false store_key="KVStoreKey{0xc0005849e0, txfees}" version=0
5:05PM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false store_key="KVStoreKey{0xc000584960, capability}" version=0
5:05PM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false store_key="KVStoreKey{0xc0005849d0, authz}" version=0
5:05PM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false store_key="KVStoreKey{0xc0005848e0, slashing}" version=0
5:05PM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false store_key="KVStoreKey{0xc000584940, evidence}" version=0
5:05PM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false store_key="KVStoreKey{0xc000584930, upgrade}" version=0
5:05PM INF service start impl=multiAppConn module=proxy msg={}
5:05PM INF service start connection=query impl=localClient module=abci-client msg={}
5:05PM INF service start connection=snapshot impl=localClient module=abci-client msg={}
5:05PM INF service start connection=mempool impl=localClient module=abci-client msg={}
5:05PM INF service start connection=consensus impl=localClient module=abci-client msg={}
5:05PM INF service start impl=EventBus module=events msg={}
5:05PM INF service start impl=PubSub module=pubsub msg={}
5:05PM INF service start impl=IndexerService module=txindex msg={}
5:05PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=
5:05PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
5:05PM INF initializing blockchain state from genesis.json
5:05PM INF running initialization for module module=capability
5:05PM INF running initialization for module module=auth
5:05PM INF running initialization for module module=bank
5:05PM INF running initialization for module module=distribution
5:05PM INF running initialization for module module=staking
5:05PM INF running initialization for module module=slashing
5:05PM INF running initialization for module module=gov
5:05PM INF running initialization for module module=mint
5:05PM INF minted coins from module account amount=225000000000000stake from=developer_vesting_unvested module=x/bank
5:05PM INF running initialization for module module=crisis
5:05PM INF asserting crisis invariants inv=1/16 module=x/crisis name=bank/nonnegative-outstanding
5:05PM INF asserting crisis invariants inv=2/16 module=x/crisis name=bank/total-supply
5:05PM INF asserting crisis invariants inv=3/16 module=x/crisis name=gov/module-account
5:05PM INF asserting crisis invariants inv=4/16 module=x/crisis name=distribution/nonnegative-outstanding
5:05PM INF asserting crisis invariants inv=5/16 module=x/crisis name=distribution/can-withdraw
5:05PM INF asserting crisis invariants inv=6/16 module=x/crisis name=distribution/reference-count
5:05PM INF asserting crisis invariants inv=7/16 module=x/crisis name=distribution/module-account
5:05PM INF asserting crisis invariants inv=8/16 module=x/crisis name=gamm/pool-account-balance-equals-expected
5:05PM INF asserting crisis invariants inv=9/16 module=x/crisis name=lockup/synthetic-lockup-invariant
5:05PM INF asserting crisis invariants inv=10/16 module=x/crisis name=lockup/accumulation-store-invariant
5:05PM INF asserting crisis invariants inv=11/16 module=x/crisis name=lockup/locks-amount-invariant
5:05PM INF asserting crisis invariants inv=12/16 module=x/crisis name=staking/module-accounts
5:05PM INF asserting crisis invariants inv=13/16 module=x/crisis name=staking/nonnegative-power
5:05PM INF asserting crisis invariants inv=14/16 module=x/crisis name=staking/positive-delegation
5:05PM INF asserting crisis invariants inv=15/16 module=x/crisis name=staking/delegator-shares
5:05PM INF asserting crisis invariants inv=16/16 module=x/crisis name=superfluid/total-superfluid-delegation-invariant-name
5:05PM INF asserted all invariants duration=1.202391 height=0 module=x/crisis
5:05PM INF running initialization for module module=ibc
5:05PM INF running initialization for module module=interchainaccounts
5:05PM INF created new capability module=ibc name=ports/icahost
5:05PM INF port binded module=x/ibc/port port=icahost
5:05PM INF claimed capability capability=1 module=icahost name=ports/icahost
5:05PM INF running initialization for module module=gamm
5:05PM INF running initialization for module module=twap
5:05PM INF running initialization for module module=txfees
5:05PM INF running initialization for module module=genutil
5:05PM INF running initialization for module module=evidence
5:05PM INF running initialization for module module=upgrade
5:05PM INF running initialization for module module=vesting
5:05PM INF running initialization for module module=transfer
5:05PM INF created new capability module=ibc name=ports/transfer
5:05PM INF port binded module=x/ibc/port port=transfer
5:05PM INF claimed capability capability=2 module=transfer name=ports/transfer
5:05PM INF running initialization for module module=poolincentives
5:05PM INF running initialization for module module=superfluid
5:05PM INF running initialization for module module=tokenfactory
5:05PM INF running initialization for module module=incentives
5:05PM INF running initialization for module module=epochs
5:05PM INF running initialization for module module=lockup
5:05PM INF running initialization for module module=authz
5:05PM INF running initialization for module module=wasm
5:05PM INF Done init genesis
Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain
````

**Comment by atomlab** [comment]
I have download genesis.json again from `https://github.com/osmosis-labs/networks/raw/main/osmosis-1/genesis.json`  and faced another error. 

```
# osmosisd start --home /
6:27PM INF starting ABCI with Tendermint
6:27PM INF service start impl=multiAppConn module=proxy msg={}
6:27PM INF service start connection=query impl=localClient module=abci-client msg={}
6:27PM INF service start connection=snapshot impl=localClient module=abci-client msg={}
6:27PM INF service start connection=mempool impl=localClient module=abci-client msg={}
6:27PM INF service start connection=consensus impl=localClient module=abci-client msg={}
6:27PM INF service start impl=EventBus module=events msg={}
6:27PM INF service start impl=PubSub module=pubsub msg={}
6:27PM INF service start impl=IndexerService module=txindex msg={}
6:27PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=
6:27PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
6:27PM INF initializing blockchain state from genesis.json
6:27PM INF running initialization for module module=capability
6:27PM INF running initialization for module module=auth
6:27PM INF running initialization for module module=bank
6:27PM INF running initialization for module module=distribution
6:27PM INF running initialization for module module=staking
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x118115d]

goroutine 1 [running]:
math/big.(*Int).Sign(...)
	math/big/int.go:39
github.com/cosmos/cosmos-sdk/types.Int.IsNegative(...)
	github.com/cosmos/cosmos-sdk@v0.46.1/types/int.go:194
github.com/cosmos/cosmos-sdk/x/staking/types.validateMinSelfDelegation({0x249d940?, 0x0?})
	github.com/cosmos/cosmos-sdk@v0.46.1/x/staking/types/params.go:254 +0x3d
github.com/cosmos/cosmos-sdk/x/params/types.Subspace.SetParamSet({{0x2b3f6d8, 0xc0001e0dc0}, 0xc000010270, {0x2b19d90, 0xc000f54250}, {0x2b19de0, 0xc000f54430}, {0xc001634348, 0x7, 0x18}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.1/x/params/types/subspace.go:236 +0x185
github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.SetParams(...)
	github.com/cosmos/cosmos-sdk@v0.46.1/x/staking/keeper/params.go:77
github.com/cosmos/cosmos-sdk/x/staking.InitGenesis({{0x2b31540, 0xc000054048}, {0x2b41400, 0xc00004f0c0}, {{0x0, 0x0}, {0xc000f58010, 0x9}, 0x0, {0x0, ...}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.1/x/staking/genesis.go:35 +0x1ec
github.com/cosmos/cosmos-sdk/x/staking.AppModule.InitGenesis({{{0x2b42ea8, 0xc0001e0dc0}}, {{0x2b19d90, 0xc000f54200}, {0x2b3f6d8, 0xc0001e0dc0}, {0x2b33800, 0xc00026ed80}, {0x2b3d098, 0xc000ebd340}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.1/x/staking/module.go:154 +0x145
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x2b31540, 0xc000054048}, {0x2b41400, 0xc00004f0c0}, {{0x0, 0x0}, {0xc000f58010, 0x9}, 0x0, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.1/types/module/module.go:322 +0x429
github.com/osmosis-labs/osmosis/v12/app.(*OsmosisApp).InitChainer(_, {{0x2b31540, 0xc000054048}, {0x2b41400, 0xc00004f0c0}, {{0x0, 0x0}, {0xc000f58010, 0x9}, 0x0, ...}, ...}, ...)
	github.com/osmosis-labs/osmosis/v12/app/app.go:335 +0x1b5
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc0001c2a80, {{0x0, 0xed85ec810, 0x0}, {0xc000f58010, 0x9}, 0xc000516c80, {0x3d4bb98, 0x0, 0x0}, ...})
	github.com/cosmos/cosmos-sdk@v0.46.1/baseapp/abci.go:85 +0x515
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc000f4df80, {{0x0, 0xed85ec810, 0x0}, {0xc000f58010, 0x9}, 0xc000516c80, {0x3d4bb98, 0x0, 0x0}, ...})
	github.com/tendermint/tendermint@v0.34.21/abci/client/local_client.go:272 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x0?, {{0x0, 0xed85ec810, 0x0}, {0xc000f58010, 0x9}, 0xc000516c80, {0x3d4bb98, 0x0, 0x0}, ...})
	github.com/tendermint/tendermint@v0.34.21/proxy/app_conn.go:77 +0x55
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x24d69e2, 0x7}}, {0xc000f58010, 0x9}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.21/consensus/replay.go:319 +0xd78
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc006df3920, {0x2b41bd8, 0xc000519380})
	github.com/tendermint/tendermint@v0.34.21/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x24d69e2, 0x7}}, {0xc000f58010, 0x9}, 0x1, 0x0, ...}, ...)
	github.com/tendermint/tendermint@v0.34.21/node/node.go:330 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc000dadb80, {0x2b2e3a8, 0xc0011603c0}, 0xc000e6c520, {0x2b14e20, 0xc000598a98}, 0x1?, 0x0?, 0xc000e6c6a0, {0x2b32928, ...}, ...)
	github.com/tendermint/tendermint@v0.34.21/node/node.go:778 +0x597
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x2b48d18, 0xc000f40090}, {0x0, 0x0}, {0x2b36820, 0xc000e6c610}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.1/server/start.go:264 +0x7bb
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc00016ac00?, {0xc000517fa0?, 0x0?, 0x2?})
	github.com/cosmos/cosmos-sdk@v0.46.1/server/start.go:128 +0x193
github.com/spf13/cobra.(*Command).execute(0xc00016ac00, {0xc000517f80, 0x2, 0x2})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000eb8300)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.6.1/command.go:961
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc00011beb0, 0xf})
	github.com/cosmos/cosmos-sdk@v0.46.1/server/cmd/execute.go:36 +0x1eb
main.main()
	./main.go:16 +0x31
```

**Comment by czarcas7ic** [comment]
my guess is you are syncing from genesis with the wrong version, or you are trying to sync from v12 with no snapshot. If you haven't already, utilize https://get.osmosis.zone

**Comment by atomlab** [comment]
> my guess is you are syncing from genesis with the wrong version, or you are trying to sync from v12 with no snapshot. If you haven't already, utilize https://get.osmosis.zone

Thanks a lot! I have downloaded `default` snapshot from there https://dl2.quicksync.io/json/osmosis.json and it helped me!

**Comment by czarcas7ic** [comment]
@atomlab glad it helped! :)
