### ISSUE TITLE
Issue with update Osmosis Node to version 13.1.0

### ISSUE THREAD

**Issue by slider90** [osmosis-labs/osmosis#3651]
#### System information

Osmosis version: `13.1.0`
OS & Version: Linux

#### Expected behaviour
Osmosis node is working well

#### Actual behaviour
After updating node version from 12.3.0 to 13.0.0 node stopped to import new blocks.
So we decided to proceed upgrading to version 13.1.0 and the node started failing with the error invalid block: wrong Block.Header.LastResultsHash

#### Steps to reproduce the behaviour
1. Upgrade node from version 12.3.0 to 13.0.0

#### Backtrace

Last logs from  node with version 13.0.0. And no any lines with importing blocks.
````
> 12:14PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=6 numToDial=4
12:14PM INF Dialing peer address={“id”:“08a794cd4d5ecd5f2deb72c3b92ad68ba69af0bf”,“ip”:“3.142.233.132",“port”:26802} module=p2p
12:14PM INF Dialing peer address={“id”:“ed59d34439a5f0738067ab8526c6c967116697df”,“ip”:“44.228.128.124”,“port”:46656} module=p2p
12:14PM INF Dialing peer address={“id”:“9c3f1cf2a925f2b61b765425ae3b4a08a8cda891",“ip”:“35.183.94.66",“port”:26656} module=p2p
12:14PM INF Dialing peer address={“id”:“810eed08107a1c9c8967730557a3f112730abf5b”,“ip”:“3.67.198.237”,“port”:26656} module=p2p
````
And error: 
````
> 12:06PM INF service stop impl={“Logger”:{}} module=p2p msg={} peer={“id”:“eec35e563f3095b0eed4705aec5e3c6c4bdb2981”,“ip”:“162.55.192.254”,“port”:34656}
12:06PM ERR Stopping peer for error err=“read tcp 172.21.0.2:43924->162.55.192.254:34656: read: connection reset by peer” module=p2p peer={“Data”:{},“Logger”:{}}
````

After upgrading node to version 13.1.0 - node started failing with the following error:
````
> 4:20PM INF Replay: Vote blockID={"hash":"F128D2B6A91F45A8CC71A6BFD6CBD03D849279578940DADF1365368920300D64","parts":{"hash":"6F1C52CFB6F77F31479E6321F834FBD0D1A9776CD338F3A65DED0FDE22970BA6","total":1}} height=7225355 module=consensus peer=fc590afe489a1b9ca8ff3f2fb396dbc20b1997a4 round=0 type=2
4:20PM INF Replay: Vote blockID={"hash":"F128D2B6A91F45A8CC71A6BFD6CBD03D849279578940DADF1365368920300D64","parts":{"hash":"6F1C52CFB6F77F31479E6321F834FBD0D1A9776CD338F3A65DED0FDE22970BA6","total":1}} height=7225355 module=consensus peer=fc590afe489a1b9ca8ff3f2fb396dbc20b1997a4 round=0 type=2
4:20PM INF Replay: BlockPart height=7225355 module=consensus peer=fc590afe489a1b9ca8ff3f2fb396dbc20b1997a4 round=0
4:20PM INF received complete proposal block hash=F128D2B6A91F45A8CC71A6BFD6CBD03D849279578940DADF1365368920300D64 height=7225355 module=consensus
panic: +2/3 committed an invalid block: wrong Block.Header.LastResultsHash.  Expected ABA8CD51E5B4630E6443BD1E79373A4C81FB04C70A6AB86C14222B5EFA91E181, got A5894FC9ED09C26FF50A9333D8EABA0905C2987A6F0787560DBE81D8696E2BFB

goroutine 1 [running]:
github.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc000ef7880, 0x6e400b)
        github.com/tendermint/tendermint@v0.34.22/consensus/state.go:1599 +0x1105
github.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc000ef7880, 0x6e400b)
        github.com/tendermint/tendermint@v0.34.22/consensus/state.go:1568 +0x2ff
github.com/tendermint/tendermint/consensus.(*State).handleCompleteProposal(0xc000ef7880, 0x0?)
        github.com/tendermint/tendermint@v0.34.22/consensus/state.go:1947 +0x399
github.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc000ef7880, {{0x2cd6b40?, 0xc02046db90?}, {0xcafdbe4e10?, 0xc04ecf9818?}})
        github.com/tendermint/tendermint@v0.34.22/consensus/state.go:837 +0x1c5
github.com/tendermint/tendermint/consensus.(*State).readReplayMessage(0xc000ef7880, 0x268dd3b?, {0x0?, 0x0?})
        github.com/tendermint/tendermint@v0.34.22/consensus/replay.go:81 +0x87f
github.com/tendermint/tendermint/consensus.(*State).catchupReplay(0xc000ef7880, 0x6e400b)
        github.com/tendermint/tendermint@v0.34.22/consensus/replay.go:160 +0x71d
github.com/tendermint/tendermint/consensus.(*State).OnStart(0xc000ef7880)
        github.com/tendermint/tendermint@v0.34.22/consensus/state.go:324 +0x19b
github.com/tendermint/tendermint/libs/service.(*BaseService).Start(0xc000ef7880)
        github.com/tendermint/tendermint@v0.34.22/libs/service/service.go:144 +0x2e9
github.com/tendermint/tendermint/consensus.(*Reactor).OnStart(0xc00012b0e0)
        github.com/tendermint/tendermint@v0.34.22/consensus/reactor.go:86 +0x145
github.com/tendermint/tendermint/libs/service.(*BaseService).Start(0xc00012b0e0)
        github.com/tendermint/tendermint@v0.34.22/libs/service/service.go:144 +0x2e9
github.com/tendermint/tendermint/p2p.(*Switch).OnStart(0xc000fed0e0)
        github.com/tendermint/tendermint@v0.34.22/p2p/switch.go:227 +0x9c
github.com/tendermint/tendermint/libs/service.(*BaseService).Start(0xc000fed0e0)
        github.com/tendermint/tendermint@v0.34.22/libs/service/service.go:144 +0x2e9
github.com/tendermint/tendermint/node.(*Node).OnStart(0xcaf07aa2c0)
        github.com/tendermint/tendermint@v0.34.22/node/node.go:979 +0x38b
github.com/tendermint/tendermint/libs/service.(*BaseService).Start(0xcaf07aa2c0)
        github.com/tendermint/tendermint@v0.34.22/libs/service/service.go:144 +0x2e9
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x2d0d058, 0xc000f416e0}, {0x0, 0x0}, {0x2cfa070, 0xc0000a3930}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.45.11/server/start.go:279 +0x815
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc00036d200?, {0xc0010e0d20?, 0x0?, 0x7?})
        github.com/cosmos/cosmos-sdk@v0.45.11/server/start.go:128 +0x193
github.com/spf13/cobra.(*Command).execute(0xc00036d200, {0xc0010e0cb0, 0x7, 0x7})
        github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000f65500)
        github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.6.1/command.go:961
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc0002379f8, 0x12})
        github.com/cosmos/cosmos-sdk@v0.45.11/server/cmd/execute.go:36 +0x1eb
main.main()
        ./main.go:16 +0x31
````

When submitting logs: please submit them as text and not screenshots.

**Comment by ValarDragon** [comment]
Wait you can't upgrade until the upgrade height?

The upgrade is happening tomorrow. Perhaps use cosmovisor to automate upgrading, there are cosmovisor upgrade instructions in the governance proposal.

To recover this node, you will likely have to resync the node, until reverting a nodes state by one height lands.

**Comment by ValarDragon** [comment]
You can resync via https://get.osmosis.zone/

or downloading a chainlayer snapshot https://quicksync.io/networks/osmosis.html

**Comment by dzmitrykliapkou** [comment]
@ValarDragon how can we know the exact date to update nodes if it is not mentioned in the release notes?
