### ISSUE TITLE
Node does not start

### ISSUE THREAD

**Issue by tazhate** [osmosis-labs/osmosis#4228]
#### System information

Osmosis version:14.0.0
OS & Version: Ubuntu 22.04.1 LTS

#### Expected behaviour

Node started.

#### Actual behaviour

Node cannot start

#### Steps to reproduce the behaviour

Just installed everything via standard installer
#### Backtrace

````
9:24PM INF initializing blockchain state from genesis.json
9:24PM INF running initialization for module module=capability
9:24PM INF running initialization for module module=auth
9:24PM INF running initialization for module module=bank
9:24PM INF running initialization for module module=distribution
9:24PM INF running initialization for module module=staking
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x11fc39d]

goroutine 1 [running]:
math/big.(*Int).Sign(...)
	math/big/int.go:38
github.com/cosmos/cosmos-sdk/types.Int.IsNegative(...)
	github.com/cosmos/cosmos-sdk@v0.46.7/types/int.go:194
github.com/cosmos/cosmos-sdk/x/staking/types.validateMinSelfDelegation({0x2058940?, 0x0?})
	github.com/cosmos/cosmos-sdk@v0.46.7/x/staking/types/params.go:254 +0x3d
github.com/cosmos/cosmos-sdk/x/params/types.Subspace.SetParamSet({{0x277c7e0, 0xc00122cc20}, 0xc000015fa0, {0x274f9d8, 0xc00118e310}, {0x274fa28, 0xc00118e440}, {0xc0011f8f18, 0x7, 0x18}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.7/x/params/types/subspace.go:236 +0x185
github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.SetParams(...)
	github.com/cosmos/cosmos-sdk@v0.46.7/x/staking/keeper/params.go:77
github.com/cosmos/cosmos-sdk/x/staking.InitGenesis({{0x27695a8, 0xc0000560e0}, {0x277eda0, 0xc000115980}, {{0x0, 0x0}, {0xc000118170, 0x9}, 0x0, {0x0, ...}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.7/x/staking/genesis.go:35 +0x1ec
github.com/cosmos/cosmos-sdk/x/staking.AppModule.InitGenesis({{{0x2782840, 0xc00122cc20}}, {{0x274f9d8, 0xc00118e2b0}, {0x277c7e0, 0xc00122cc20}, {0x276c480, 0xc001282360}, {0x2779640, 0xc000593a20}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.7/x/staking/module.go:154 +0x145
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x27695a8, 0xc0000560e0}, {0x277eda0, 0xc000115980}, {{0x0, 0x0}, {0xc000118170, 0x9}, 0x0, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.7/types/module/module.go:322 +0x429
github.com/osmosis-labs/osmosis/v14/app.(*OsmosisApp).InitChainer(_, {{0x27695a8, 0xc0000560e0}, {0x277eda0, 0xc000115980}, {{0x0, 0x0}, {0xc000118170, 0x9}, 0x0, ...}, ...}, ...)
	github.com/osmosis-labs/osmosis/v14/app/app.go:355 +0x1b5
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000e57520, {{0x0, 0xed85ec810, 0x0}, {0xc000118170, 0x9}, 0xc000117b80, {0x3897198, 0x0, 0x0}, ...})
	github.com/cosmos/cosmos-sdk@v0.46.7/baseapp/abci.go:85 +0x515
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc000e72c00, {{0x0, 0xed85ec810, 0x0}, {0xc000118170, 0x9}, 0xc000117b80, {0x3897198, 0x0, 0x0}, ...})
	github.com/tendermint/tendermint@v0.34.24/abci/client/local_client.go:272 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x0?, {{0x0, 0xed85ec810, 0x0}, {0xc000118170, 0x9}, 0xc000117b80, {0x3897198, 0x0, 0x0}, ...})
	github.com/tendermint/tendermint@v0.34.24/proxy/app_conn.go:77 +0x55
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x20a2f9b, 0x7}}, {0xc000118170, 0x9}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.24/consensus/replay.go:319 +0xd78
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0002c3920, {0x277fa20, 0xc00059a1a0})
	github.com/tendermint/tendermint@v0.34.24/consensus/replay.go:268 +0x3d4
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x20a2f9b, 0x7}}, {0xc000118170, 0x9}, 0x1, 0x0, ...}, ...)
	github.com/tendermint/tendermint@v0.34.24/node/node.go:329 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc000250dc0, {0x27658a0, 0xc00021ae60}, 0xc00122d870, {0x27493a0, 0xc000e6cbe8}, 0x1?, 0x0?, 0xc00122d9d0, {0x276aaa8, ...}, ...)
	github.com/tendermint/tendermint@v0.34.24/node/node.go:777 +0x597
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x278c818, 0xc0012df590}, {0x0, 0x0}, {0x27718f0, 0xc001249e20}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.7/server/start.go:264 +0x7bb
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc0012ce000?, {0xc000200ca0?, 0x0?, 0x2?})
	github.com/cosmos/cosmos-sdk@v0.46.7/server/start.go:128 +0x193
github.com/spf13/cobra.(*Command).execute(0xc0012ce000, {0xc000200c80, 0x2, 0x2})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000e7db00)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.6.1/command.go:961
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc0012521c0, 0xf})
	github.com/cosmos/cosmos-sdk@v0.46.7/server/cmd/execute.go:36 +0x1eb
main.main()
	github.com/osmosis-labs/osmosis/v14/cmd/osmosisd/main.go:16 +0x31

````

**Comment by mattverse** [comment]
Thanks for the issue @tazhate ! Were you using Osmosis Installer with the node type of Local Osmosis Node? Were there any specific actions that you took after installing and starting the node? (Just trying to replicate the issue you ran into)

**Comment by tazhate** [comment]
@mattverse i'm trying to install full node, only custom option was selected is another path for files. Other options is default/recommended

**Comment by mattverse** [comment]
Can't seem to replicate bug in my local environment, perhaps linking us to `genesis.json` under ./osmosisd/config might help us better to debug this issue (we only need the staking params part from genesis.json (that looks something like the code block below) since thats where the problem seems to occur
```
 "staking": {
      "params": {
        "unbonding_time": "1209600s",
        "max_validators": 100,
        "max_entries": 7,
        "historical_entries": 10000,
        "bond_denom": "uosmo",
        "min_commission_rate": "0.050000000000000000"
      },
      "last_total_power": "0",
      "last_validator_powers": [],
      "validators": [],
      "delegations": [],
      "unbonding_delegations": [],
      "redelegations": [],
      "exported": false
    },
```

**Comment by ValarDragon** [comment]
So there was a bug in osmosis-installer, the fix just got merged.

Could you retry running the installer?

**Comment by jadechip** [comment]
I am also getting this by installing manually (downloading a binary) and running osmosisd start.

**Comment by ValarDragon** [comment]
Re-reading, this is definitely the error caused due to the osmosis-installer break in downloading snapshots, which has been fixed.

@jadechip the problem your running into in #4269 is the same error, but for a different reason (wanting something different, rather than an installer bug) 

Closing this, please re-open if im wrong!
