### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jadechip** [osmosis-labs/osmosis#4269]
#### System information

Osmosis version: v14.0.0.0
OS & Version: Amazon Linux 2

Using the latest binaries, and following the instructions from https://docs.osmosis.zone/networks/join-mainnet/
I get the following error when running `osmosisd start`.

I've downloaded the genesis file from here:
```
wget -O ~/.osmosisd/config/genesis.json https://github.com/osmosis-labs/networks/raw/main/osmosis-1/genesis.json
```
I am trying to run an archive node and need it up and running asap also any and all help would be greatly appreciated.

```
4:06AM INF starting ABCI with Tendermint
4:06AM INF service start impl=multiAppConn module=proxy msg={}
4:06AM INF service start connection=query impl=localClient module=abci-client msg={}
4:06AM INF service start connection=snapshot impl=localClient module=abci-client msg={}
4:06AM INF service start connection=mempool impl=localClient module=abci-client msg={}
4:06AM INF service start connection=consensus impl=localClient module=abci-client msg={}
4:06AM INF service start impl=EventBus module=events msg={}
4:06AM INF service start impl=PubSub module=pubsub msg={}
4:06AM INF service start impl=IndexerService module=txindex msg={}
4:06AM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=14.0.0
4:06AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
4:06AM INF initializing blockchain state from genesis.json
4:06AM INF running initialization for module module=capability
4:06AM INF running initialization for module module=auth
4:06AM INF running initialization for module module=bank
4:06AM INF running initialization for module module=distribution
4:06AM INF running initialization for module module=staking
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1216e7d]

goroutine 1 [running]:
math/big.(*Int).Sign(...)
	math/big/int.go:38
github.com/cosmos/cosmos-sdk/types.Int.IsNegative(...)
	github.com/cosmos/cosmos-sdk@v0.46.7/types/int.go:194
github.com/cosmos/cosmos-sdk/x/staking/types.validateMinSelfDelegation({0x2681ac0?, 0x0?})
	github.com/cosmos/cosmos-sdk@v0.46.7/x/staking/types/params.go:254 +0x3d
github.com/cosmos/cosmos-sdk/x/params/types.Subspace.SetParamSet({{0x2da5d40, 0xc001008550}, 0xc00020f8a8, {0x2d78f38, 0xc0014cc740}, {0x2d78f88, 0xc0014cc870}, {0xc0014aa480, 0x7, 0x18}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.7/x/params/types/subspace.go:236 +0x185
github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.SetParams(...)
	github.com/cosmos/cosmos-sdk@v0.46.7/x/staking/keeper/params.go:77
github.com/cosmos/cosmos-sdk/x/staking.InitGenesis({{0x2d92b08, 0xc00005a048}, {0x2da8300, 0xc0014d0a80}, {{0x0, 0x0}, {0xc000154050, 0x9}, 0x0, {0x0, ...}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.7/x/staking/genesis.go:35 +0x1ec
github.com/cosmos/cosmos-sdk/x/staking.AppModule.InitGenesis({{{0x2dabda0, 0xc001008550}}, {{0x2d78f38, 0xc0014cc6e0}, {0x2da5d40, 0xc001008550}, {0x2d959e0, 0xc0011be1b0}, {0x2da2ba0, 0xc0012bbe40}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.7/x/staking/module.go:154 +0x145
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x2d92b08, 0xc00005a048}, {0x2da8300, 0xc0014d0a80}, {{0x0, 0x0}, {0xc000154050, 0x9}, 0x0, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.7/types/module/module.go:322 +0x429
github.com/osmosis-labs/osmosis/v14/app.(*OsmosisApp).InitChainer(_, {{0x2d92b08, 0xc00005a048}, {0x2da8300, 0xc0014d0a80}, {{0x0, 0x0}, {0xc000154050, 0x9}, 0x0, ...}, ...}, ...)
	github.com/osmosis-labs/osmosis/v14/app/app.go:355 +0x1b5
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc0012e5520, {{0x0, 0xed85ec810, 0x0}, {0xc000154050, 0x9}, 0xc00147ca00, {0x40d1618, 0x0, 0x0}, ...})
	github.com/cosmos/cosmos-sdk@v0.46.7/baseapp/abci.go:85 +0x515
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc0002be4e0, {{0x0, 0xed85ec810, 0x0}, {0xc000154050, 0x9}, 0xc00147ca00, {0x40d1618, 0x0, 0x0}, ...})
	github.com/tendermint/tendermint@v0.34.24/abci/client/local_client.go:272 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x0?, {{0x0, 0xed85ec810, 0x0}, {0xc000154050, 0x9}, 0xc00147ca00, {0x40d1618, 0x0, 0x0}, ...})
	github.com/tendermint/tendermint@v0.34.24/proxy/app_conn.go:77 +0x55
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x26cc3db, 0x7}}, {0xc000154050, 0x9}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.24/consensus/replay.go:319 +0xd78
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc001937920, {0x2da8f80, 0xc000ef0680})
	github.com/tendermint/tendermint@v0.34.24/consensus/replay.go:268 +0x3d4
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x26cc3db, 0x7}}, {0xc000154050, 0x9}, 0x1, 0x0, ...}, ...)
	github.com/tendermint/tendermint@v0.34.24/node/node.go:329 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc001063900, {0x2d8ee00, 0xc0012ebc20}, 0xc00020db40, {0x2d72900, 0xc0002327e0}, 0x1?, 0x0?, 0xc00020dca0, {0x2d94008, ...}, ...)
	github.com/tendermint/tendermint@v0.34.24/node/node.go:777 +0x597
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x2db5d78, 0xc0012e8d50}, {0x0, 0x0}, {0x2d9ae50, 0xc00102f750}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.7/server/start.go:264 +0x7bb
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc0010ab200?, {0xc0011efb00?, 0x0?, 0x2?})
	github.com/cosmos/cosmos-sdk@v0.46.7/server/start.go:128 +0x193
github.com/spf13/cobra.(*Command).execute(0xc0010ab200, {0xc0011efae0, 0x2, 0x2})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000fe6f00)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.6.1/command.go:961
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc00012aea0, 0x17})
	github.com/cosmos/cosmos-sdk@v0.46.7/server/cmd/execute.go:36 +0x1eb
main.main()
	./main.go:16 +0x31
```

**Comment by ValarDragon** [comment]
You can't use v14.0.0 to sync from genesis unfortunately. The binary has to be switched at every upgrade height. There is some tooling to automate this.

Highly recommend using get.osmosis.zone for setting up an archive node, it can configure cosmovisor to sync through all blocks from genesis/
