### ISSUE TITLE
Full node crashed with too many open files

### ISSUE THREAD

**Issue by swordfish2007** [osmosis-labs/osmosis#603]
I'm on 4.2.0. I use the pruned snapshot from [quicksync](https://quicksync.io/networks/osmosis.html) and the address book from [them](https://quicksync.io/addrbook.osmosis.json) to start a full node.

Everything is fine in the beginning and I see the node is catching up and syncing blocks with the network.

However, after a while like few hours, I can only see all the dialing failed errors and the node is no longer syncing. Here is a snapshot of the output:

```
5:32PM INF Dialing peer address={"id":"38c0f82fc9e7a825c0155555b1eb9a47275b859d","ip":"35.157.193.2","port":26656} module=p2p
5:32PM INF Dialing peer address={"id":"593b269614ec7e7de98c8d0253252f3df9e715c0","ip":"139.178.68.79","port":30496} module=p2p
5:32PM INF Dialing peer address={"id":"098f4763954f6a3545756e55aa76b7e9d539a050","ip":"94.130.238.34","port":26656} module=p2p
5:32PM INF Dialing peer address={"id":"da8c89aca6cf55401bbfc71f5eee05a5471597eb","ip":"49.12.156.40","port":26656} module=p2p
5:32PM INF Dialing peer address={"id":"fbf89f1a220f674899e984e02f3fa9fb7e45fe87","ip":"103.224.168.29","port":2000} module=p2p
5:32PM INF Dialing peer address={"id":"5b90a530464885fd28c31f698c81694d0b4a1982","ip":"35.183.238.70","port":26656} module=p2p
5:32PM INF Dialing peer address={"id":"3620237f1bf58d44a12ad9659a0e8205b72046ea","ip":"18.185.116.170","port":29656} module=p2p
5:32PM INF Dialing peer address={"id":"b13b549144446642f6d9d6d7ca48f4859aff5d05","ip":"13.58.138.71","port":26656} module=p2p
5:32PM INF Dialing peer address={"id":"504f8588f6f363c7dd48c84a36c0d5a9e7cec0ce","ip":"34.243.135.117","port":26656} module=p2p
5:32PM ERR dialing failed (attempts: 5): dial tcp 139.178.68.79:30496: connect: connection refused addr={"id":"593b269614ec7e7de98c8d0253252f3df9e715c0","ip":"139.178.68.79","port":30496} module=pex
5:32PM ERR dialing failed (attempts: 5): dial tcp 34.243.135.117:26656: connect: connection refused addr={"id":"504f8588f6f363c7dd48c84a36c0d5a9e7cec0ce","ip":"34.243.135.117","port":26656} module=pex
5:32PM ERR dialing failed (attempts: 6): dial tcp 35.157.193.2:26656: i/o timeout addr={"id":"38c0f82fc9e7a825c0155555b1eb9a47275b859d","ip":"35.157.193.2","port":26656} module=pex
5:32PM ERR dialing failed (attempts: 2): dial tcp 94.130.238.34:26656: i/o timeout addr={"id":"098f4763954f6a3545756e55aa76b7e9d539a050","ip":"94.130.238.34","port":26656} module=pex
5:32PM ERR dialing failed (attempts: 7): dial tcp 49.12.156.40:26656: i/o timeout addr={"id":"da8c89aca6cf55401bbfc71f5eee05a5471597eb","ip":"49.12.156.40","port":26656} module=pex
5:32PM ERR dialing failed (attempts: 7): dial tcp 103.224.168.29:2000: i/o timeout addr={"id":"fbf89f1a220f674899e984e02f3fa9fb7e45fe87","ip":"103.224.168.29","port":2000} module=pex
5:32PM ERR dialing failed (attempts: 6): dial tcp 35.183.238.70:26656: i/o timeout addr={"id":"5b90a530464885fd28c31f698c81694d0b4a1982","ip":"35.183.238.70","port":26656} module=pex
5:32PM ERR dialing failed (attempts: 2): dial tcp 13.58.138.71:26656: i/o timeout addr={"id":"b13b549144446642f6d9d6d7ca48f4859aff5d05","ip":"13.58.138.71","port":26656} module=pex
5:32PM ERR dialing failed (attempts: 3): dial tcp 18.185.116.170:29656: i/o timeout addr={"id":"3620237f1bf58d44a12ad9659a0e8205b72046ea","ip":"18.185.116.170","port":29656} module=pex
```

Any suggestions? Am I using the right address book? Or is it possibly related to [#545] ?

Thanks.

**UPDATE**
The node finally crashed with this TOO MANY OPEN FILES error:

```
10:08PM INF Will dial address addr={"id":"a7d1dd50006fa80bed1c1f5769b5df36ef171af0","ip":"35.158.102.16","port":29656} module=pex
10:08PM INF Will dial address addr={"id":"b4df042182f7c4e1ebcc537e721b9d7f0f8d9c76","ip":"51.15.82.190","port":26656} module=pex
10:08PM INF Will dial address addr={"id":"b532bc8b1c38e9c72485f5a7c6b22339dac9a325","ip":"3.67.189.65","port":29656} module=pex
10:08PM INF Will dial address addr={"id":"beab9e331c062c78c256e2dd193e4af991cfd4f6","ip":"14.199.56.25","port":36656} module=pex
10:08PM INF Will dial address addr={"id":"18af72a5b949343d0e242c70d87225d9c47867b6","ip":"3.121.86.113","port":26656} module=pex
10:08PM INF Will dial address addr={"id":"3cb7f784aef7c657d0ca44511155f6085c38ad2a","ip":"163.172.210.107","port":26656} module=pex
10:08PM INF Will dial address addr={"id":"0dc7c68de0b20ba358e3e4dd517be92d27fcab6f","ip":"159.65.162.134","port":26656} module=pex
10:08PM INF Will dial address addr={"id":"9417c41d31f330d67b3230755cbd5dfb8123f97b","ip":"172.94.32.82","port":26656} module=pex
10:08PM INF Will dial address addr={"id":"7eea530e720ca2e5ae2b4e6324d4f2a6303fc753","ip":"136.243.176.155","port":26656} module=pex
10:08PM INF Will dial address addr={"id":"da8c89aca6cf55401bbfc71f5eee05a5471597eb","ip":"49.12.156.40","port":26656} module=pex
10:08PM INF Will dial address addr={"id":"afd05547a3b703c08dbfa141305d37b454f8b647","ip":"143.198.80.32","port":26656} module=pex
10:08PM INF Will dial address addr={"id":"45ed82067a43f5ef26ee5f85ddaa12cb67488f74","ip":"3.67.12.104","port":29656} module=pex
10:08PM INF Will dial address addr={"id":"2be42b47a3a9dd2a9f956f2dcf1f04c0e0793847","ip":"3.68.159.237","port":29656} module=pex
10:08PM INF Will dial address addr={"id":"74aeb6ca5bdd6e2753a7258da3379be97787c5f7","ip":"136.244.97.210","port":26656} module=pex
10:08PM INF Will dial address addr={"id":"b88b3095442495c1b9c6c2a1215b12d2b61f9376","ip":"18.195.214.191","port":29656} module=pex
10:08PM INF Will dial address addr={"id":"d7f84dbab78f6d1a9492d3e97911eb7e8881c1d3","ip":"40.124.41.191","port":26656} module=pex
10:08PM INF Will dial address addr={"id":"f073123e8883af8602188449558cfeb4fa515cbf","ip":"164.90.184.244","port":56656} module=pex
10:08PM INF Will dial address addr={"id":"412268715d6dd3a28563bf98a11b051f9f691fe8","ip":"106.249.245.180","port":26656} module=pex
10:08PM INF Will dial address addr={"id":"7d5da67122a7005c5cdc135db68f4a8a345c50ec","ip":"35.223.161.94","port":26656} module=pex
10:08PM INF Will dial address addr={"id":"d6666028bcb7906291a82b9af59c59389ea9094c","ip":"3.64.232.196","port":29656} module=pex
10:08PM INF Will dial address addr={"id":"6937a77273960a68f7d9bcbf47b55ed2d84940fb","ip":"116.202.139.104","port":26656} module=pex
10:08PM INF Will dial address addr={"id":"3efb0e43b7d116799bdf3a0fa1da934d805ede18","ip":"65.21.35.102","port":56656} module=pex
10:08PM INF Will dial address addr={"id":"015c6bbe36eb63f8a776678e97bb5e787085c1d6","ip":"206.81.21.33","port":26656} module=pex
10:08PM INF Will dial address addr={"id":"fbbfcb3203bf401c8aff274c5f78870329bd41c5","ip":"52.60.52.207","port":26681} module=pex
10:08PM INF Will dial address addr={"id":"dc8843fc19a587010afe322c99f33b44171a9bcd","ip":"157.90.113.120","port":26656} module=pex
10:08PM INF Will dial address addr={"id":"df65b335f668b9feae5f8807ec899f96acd15d79","ip":"165.227.138.32","port":26656} module=pex
10:08PM INF Will dial address addr={"id":"37ac437bb0267736854d275bac63b395aad3e1c4","ip":"202.61.201.178","port":26657} module=pex
10:08PM INF Will dial address addr={"id":"77823a52821ac1a85cde8018ecb80add8dae87a4","ip":"54.36.62.219","port":26656} module=pex
10:08PM INF Will dial address addr={"id":"76c3cfb338a4fe3e90939e0b0bef0260056962bf","ip":"3.122.114.254","port":29656} module=pex
10:08PM INF Will dial address addr={"id":"87601e3c795ce233fedc732af01517702008cddc","ip":"177.66.67.30","port":26656} module=pex
10:08PM INF Will dial address addr={"id":"7838e9b6dddef467365c650e595e323a5ef79784","ip":"217.69.0.23","port":26656} module=pex
10:08PM INF Will dial address addr={"id":"b230aee968729daf60b3022b2fbddf56bb28c0fc","ip":"34.223.54.35","port":31643} module=pex
10:08PM INF Will dial address addr={"id":"e7916387e05acd53d1b8c0f842c13def365c7bb6","ip":"176.9.64.212","port":26666} module=pex
10:08PM INF Will dial address addr={"id":"9b822c14953f27265c2ed1540fcdc66b64e19911","ip":"8.210.56.233","port":26656} module=pex
10:08PM INF Will dial address addr={"id":"3933f0d70e5e5a26d36ad608e0875b11414bbcde","ip":"192.95.32.121","port":26656} module=pex
10:08PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
10:08PM INF Dialing peer address={"id":"dc8843fc19a587010afe322c99f33b44171a9bcd","ip":"157.90.113.120","port":26656} module=p2p
10:08PM ERR dialing failed (attempts: 4): dial tcp 157.90.113.120:26656: socket: too many open files addr={"id":"dc8843fc19a587010afe322c99f33b44171a9bcd","ip":"157.90.113.120","port":26656} module=pex
10:08PM INF Dialing peer address={"id":"0dc7c68de0b20ba358e3e4dd517be92d27fcab6f","ip":"159.65.162.134","port":26656} module=p2p
10:08PM ERR dialing failed (attempts: 1): dial tcp 159.65.162.134:26656: socket: too many open files addr={"id":"0dc7c68de0b20ba358e3e4dd517be92d27fcab6f","ip":"159.65.162.134","port":26656} module=pex
10:08PM INF Dialing peer address={"id":"d7f84dbab78f6d1a9492d3e97911eb7e8881c1d3","ip":"40.124.41.191","port":26656} module=p2p
10:08PM INF Dialing peer address={"id":"76c3cfb338a4fe3e90939e0b0bef0260056962bf","ip":"3.122.114.254","port":29656} module=p2p
10:08PM ERR dialing failed (attempts: 3): dial tcp 40.124.41.191:26656: socket: too many open files addr={"id":"d7f84dbab78f6d1a9492d3e97911eb7e8881c1d3","ip":"40.124.41.191","port":26656} module=pex
10:08PM INF Dialing peer address={"id":"6937a77273960a68f7d9bcbf47b55ed2d84940fb","ip":"116.202.139.104","port":26656} module=p2p
10:08PM ERR dialing failed (attempts: 7): dial tcp 116.202.139.104:26656: socket: too many open files addr={"id":"6937a77273960a68f7d9bcbf47b55ed2d84940fb","ip":"116.202.139.104","port":26656} module=pex
10:08PM INF Dialing peer address={"id":"412268715d6dd3a28563bf98a11b051f9f691fe8","ip":"106.249.245.180","port":26656} module=p2p
10:08PM ERR dialing failed (attempts: 3): dial tcp 106.249.245.180:26656: socket: too many open files addr={"id":"412268715d6dd3a28563bf98a11b051f9f691fe8","ip":"106.249.245.180","port":26656} module=pex
10:08PM INF Dialing peer address={"id":"3efb0e43b7d116799bdf3a0fa1da934d805ede18","ip":"65.21.35.102","port":56656} module=p2p
10:08PM INF Dialing peer address={"id":"015c6bbe36eb63f8a776678e97bb5e787085c1d6","ip":"206.81.21.33","port":26656} module=p2p
10:08PM ERR dialing failed (attempts: 4): dial tcp 206.81.21.33:26656: socket: too many open files addr={"id":"015c6bbe36eb63f8a776678e97bb5e787085c1d6","ip":"206.81.21.33","port":26656} module=pex
10:08PM INF Dialing peer address={"id":"e7916387e05acd53d1b8c0f842c13def365c7bb6","ip":"176.9.64.212","port":26666} module=p2p
10:08PM ERR dialing failed (attempts: 3): dial tcp 65.21.35.102:56656: socket: too many open files addr={"id":"3efb0e43b7d116799bdf3a0fa1da934d805ede18","ip":"65.21.35.102","port":56656} module=pex
10:08PM ERR dialing failed (attempts: 6): dial tcp 176.9.64.212:26666: socket: too many open files addr={"id":"e7916387e05acd53d1b8c0f842c13def365c7bb6","ip":"176.9.64.212","port":26666} module=pex
10:08PM INF Dialing peer address={"id":"7838e9b6dddef467365c650e595e323a5ef79784","ip":"217.69.0.23","port":26656} module=p2p
10:08PM INF Dialing peer address={"id":"77823a52821ac1a85cde8018ecb80add8dae87a4","ip":"54.36.62.219","port":26656} module=p2p
10:08PM ERR dialing failed (attempts: 12): dial tcp 54.36.62.219:26656: socket: too many open files addr={"id":"77823a52821ac1a85cde8018ecb80add8dae87a4","ip":"54.36.62.219","port":26656} module=pex
10:08PM INF Dialing peer address={"id":"74aeb6ca5bdd6e2753a7258da3379be97787c5f7","ip":"136.244.97.210","port":26656} module=p2p
10:08PM ERR dialing failed (attempts: 2): dial tcp 217.69.0.23:26656: socket: too many open files addr={"id":"7838e9b6dddef467365c650e595e323a5ef79784","ip":"217.69.0.23","port":26656} module=pex
10:08PM INF Dialing peer address={"id":"3933f0d70e5e5a26d36ad608e0875b11414bbcde","ip":"192.95.32.121","port":26656} module=p2p
10:08PM ERR dialing failed (attempts: 7): dial tcp 192.95.32.121:26656: socket: too many open files addr={"id":"3933f0d70e5e5a26d36ad608e0875b11414bbcde","ip":"192.95.32.121","port":26656} module=pex
10:08PM INF Dialing peer address={"id":"45ed82067a43f5ef26ee5f85ddaa12cb67488f74","ip":"3.67.12.104","port":29656} module=p2p
10:08PM ERR dialing failed (attempts: 9): dial tcp 136.244.97.210:26656: socket: too many open files addr={"id":"74aeb6ca5bdd6e2753a7258da3379be97787c5f7","ip":"136.244.97.210","port":26656} module=pex
10:08PM INF Dialing peer address={"id":"7eea530e720ca2e5ae2b4e6324d4f2a6303fc753","ip":"136.243.176.155","port":26656} module=p2p
10:08PM ERR dialing failed (attempts: 2): dial tcp 136.243.176.155:26656: socket: too many open files addr={"id":"7eea530e720ca2e5ae2b4e6324d4f2a6303fc753","ip":"136.243.176.155","port":26656} module=pex
10:08PM ERR dialing failed (attempts: 3): dial tcp 3.122.114.254:29656: socket: too many open files addr={"id":"76c3cfb338a4fe3e90939e0b0bef0260056962bf","ip":"3.122.114.254","port":29656} module=pex
10:08PM INF Dialing peer address={"id":"f073123e8883af8602188449558cfeb4fa515cbf","ip":"164.90.184.244","port":56656} module=p2p
10:08PM ERR dialing failed (attempts: 9): dial tcp 164.90.184.244:56656: socket: too many open files addr={"id":"f073123e8883af8602188449558cfeb4fa515cbf","ip":"164.90.184.244","port":56656} module=pex
10:08PM INF Dialing peer address={"id":"7d5da67122a7005c5cdc135db68f4a8a345c50ec","ip":"35.223.161.94","port":26656} module=p2p
10:08PM INF Dialing peer address={"id":"2be42b47a3a9dd2a9f956f2dcf1f04c0e0793847","ip":"3.68.159.237","port":29656} module=p2p
10:08PM ERR dialing failed (attempts: 3): dial tcp 35.223.161.94:26656: socket: too many open files addr={"id":"7d5da67122a7005c5cdc135db68f4a8a345c50ec","ip":"35.223.161.94","port":26656} module=pex
10:08PM ERR dialing failed (attempts: 5): dial tcp 3.68.159.237:29656: socket: too many open files addr={"id":"2be42b47a3a9dd2a9f956f2dcf1f04c0e0793847","ip":"3.68.159.237","port":29656} module=pex
10:08PM ERR dialing failed (attempts: 10): dial tcp 3.67.12.104:29656: socket: too many open files addr={"id":"45ed82067a43f5ef26ee5f85ddaa12cb67488f74","ip":"3.67.12.104","port":29656} module=pex
panic: open /home/swordfish2007/.osmosisd/data/blockstore.db/565241.ldb: too many open files

goroutine 25376870 [running]:
github.com/tendermint/tendermint/store.(*BlockStore).LoadBlockPart(0xc001080200, 0x0, 0xc023920500)
        github.com/tendermint/tendermint@v0.34.14/store/store.go:154 +0x1c5
github.com/tendermint/tendermint/consensus.(*Reactor).gossipDataForCatchup(0xc00a15a980, {0x20563a8, 0xc013c34840}, 0xc00efa7200, 0xc014e5e5a0, 0xc00a023aa0, {0x208bcf8, 0xc005569500})
        github.com/tendermint/tendermint@v0.34.14/consensus/reactor.go:606 +0x12a
github.com/tendermint/tendermint/consensus.(*Reactor).gossipDataRoutine(0xc00a15a980, {0x208bcf8, 0xc005569500}, 0xc00a21cd80)
        github.com/tendermint/tendermint@v0.34.14/consensus/reactor.go:538 +0x309
created by github.com/tendermint/tendermint/consensus.(*Reactor).AddPeer
        github.com/tendermint/tendermint@v0.34.14/consensus/reactor.go:193 +0xfd
```

**Comment by ValarDragon** [comment]
Too many open files is a standard issue folks run into with cosmos nodes. Guides for running cosmos nodes should all be sure to tell folks to increase their file size limits. One way is by doing `ulimit -n 8192` to 8x the default.

**Comment by swordfish2007** [comment]
That seems to work great now. Thanks a lot!
