### ISSUE TITLE
[Bug]: Fix CosmWasm Pools export bug and gauge not being set on creation

### ISSUE THREAD

**Issue by PaddyMc** [osmosis-labs/osmosis#6230]
### Description

Two issues arose when exporting cosmwasm pools, these need to be fixed to enable cosmwasm pools to function correctly.

See this branch for more context: https://github.com/osmosis-labs/osmosis/pull/6215

### Issue 1
```
panic: no gauge associated with pool id (86) and duration (3600000000000)

goroutine 1 [running]:
github.com/osmosis-labs/osmosis/v19/x/pool-incentives/keeper.Keeper.ExportGenesis({{0x31e7388, 0xc0020e3a40}, {{0x32197c0, 0xc001417550}, 0xc0013128d8, {0x31e7388, 0xc0020e3980}, {0x31e73d8, 0xc0020e3b20}, {0xc000453f20, ...}, ...}, ...}, ...)
	github.com/osmosis-labs/osmosis/v19/x/pool-incentives/keeper/genesis.go:60 +0x745
github.com/osmosis-labs/osmosis/v19/x/pool-incentives.AppModule.ExportGenesis({{}, {{0x31e7388, 0xc0020e3a40}, {{0x32197c0, 0xc001417550}, 0xc0013128d8, {0x31e7388, 0xc0020e3980}, {0x31e73d8, 0xc0020e3b20}, ...}, ...}}, ...)
	github.com/osmosis-labs/osmosis/v19/x/pool-incentives/module.go:143 +0x9b
github.com/cosmos/cosmos-sdk/types/module.(*Manager).ExportGenesisForModules(_, {{0x32066a8, 0xc0000560b0}, {0x321bb00, 0xc00a4c5d00}, {{0x0, 0x0}, {0x0, 0x0}, 0x249173, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.47.4/types/module/module.go:350 +0x285
github.com/osmosis-labs/osmosis/v19/app.(*OsmosisApp).ExportAppStateAndValidators(0xc0014ad200, 0x0, {0x0?, 0x0?, 0x0?}, {0x47c7c18, 0x0, 0x0})
	github.com/osmosis-labs/osmosis/v19/app/export.go:29 +0x1c5
github.com/osmosis-labs/osmosis/v19/cmd/osmosisd/cmd.createOsmosisAppAndExport({0x3207c18, 0xc0006a8420}, {0x321ac98, 0xc0002720d8}, {0x0, 0x0}, 0xffffffffffffffff, 0x18?, {0x47c7c18, 0x0, ...}, ...)
	github.com/osmosis-labs/osmosis/v19/cmd/osmosisd/cmd/root.go:631 +0x2b4
github.com/cosmos/cosmos-sdk/server.ExportCmd.func1(0xc00067f500?, {0xc00158fc20?, 0x0?, 0x2?})
	github.com/cosmos/cosmos-sdk@v0.47.4/server/export.go:73 +0x37c
github.com/spf13/cobra.(*Command).execute(0xc00067f500, {0xc00158fc00, 0x2, 0x2})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc001441200)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.7.0/command.go:985
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc0012f94d0, 0x16})
	github.com/cosmos/cosmos-sdk@v0.47.4/server/cmd/execute.go:36 +0x1eb
main.main()
	./main.go:16 +0x31
```

### Issue 2
When exporting the cosmwasm pools

```bash
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustMarshalJSON(0x32184c0?, {0x31f95a0?, 0xc8c5b71900?})
	github.com/cosmos/cosmos-sdk@v0.47.4/codec/proto_codec.go:145 +0x45
github.com/osmosis-labs/osmosis/v18/x/cosmwasmpool/module.AppModule.ExportGenesis({{{0x321e3c0, 0xc001465690}}, {{0x32184c0, 0xc001465690}, {0x31e6088, 0xc0025e4180}, {{0x32184c0, 0xc001465690}, 0xc000014c58, {0x31e6088, ...}, ...}, ...}}, ...)
	github.com/osmosis-labs/osmosis/v18/x/cosmwasmpool/module/module.go:131 +0xc2
github.com/cosmos/cosmos-sdk/types/module.(*Manager).ExportGenesisForModules(_, {{0x32053a8, 0xc0000560b0}, {0x321a800, 0xc006563840}, {{0x0, 0x0}, {0x0, 0x0}, 0x249d8e, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.47.4/types/module/module.go:350 +0x285
github.com/osmosis-labs/osmosis/v18/app.(*OsmosisApp).ExportAppStateAndValidators(0xc00114a480, 0x0, {0x0?, 0x0?, 0x0?}, {0x47c4b38, 0x0, 0x0})
	github.com/osmosis-labs/osmosis/v18/app/export.go:29 +0x1c5
github.com/osmosis-labs/osmosis/v18/cmd/osmosisd/cmd.createOsmosisAppAndExport({0x3206918, 0xc000f8c540}, {0x3219998, 0xc00160a060}, {0x0, 0x0}, 0xffffffffffffffff, 0x38?, {0x47c4b38, 0x0, ...}, ...)
	github.com/osmosis-labs/osmosis/v18/cmd/osmosisd/cmd/root.go:631 +0x2b4
github.com/cosmos/cosmos-sdk/server.ExportCmd.func1(0xc00153f500?, {0xc001683de0?, 0x0?, 0x2?})
	github.com/cosmos/cosmos-sdk@v0.47.4/server/export.go:73 +0x37c
github.com/spf13/cobra.(*Command).execute(0xc00153f500, {0xc001683dc0, 0x2, 0x2})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc00148b200)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.7.0/command.go:985
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc00134f758, 0x16})
	github.com/cosmos/cosmos-sdk@v0.47.4/server/cmd/execute.go:36 +0x1eb
main.main()
	./main.go:16 +0x31
```

### Osmosis Version

18.x, v19.x 

### How to reproduce?

Using testnet state:

- `wget -O osmotest5_2396268.tar.lz4 https://osmosis.fra1.digitaloceanspaces.com/osmo-test-5/snapshots/v18/osmotest5_2396268.tar.lz4 --inet4-only`

- checkout v18.0.0
- make install
- osmosisd export

error:
````
panic: no gauge associated with pool id (86) and duration (3600000000000)

goroutine 1 [running]:
github.com/osmosis-labs/osmosis/v19/x/pool-incentives/keeper.Keeper.ExportGenesis({{0x31e7388, 0xc0020e3a40}, {{0x32197c0, 0xc001417550}, 0xc0013128d8, {0x31e7388, 0xc0020e3980}, {0x31e73d8, 0xc0020e3b20}, {0xc000453f20, ...}, ...}, ...}, ...)
	github.com/osmosis-labs/osmosis/v19/x/pool-incentives/keeper/genesis.go:60 +0x745
github.com/osmosis-labs/osmosis/v19/x/pool-incentives.AppModule.ExportGenesis({{}, {{0x31e7388, 0xc0020e3a40}, {{0x32197c0, 0xc001417550}, 0xc0013128d8, {0x31e7388, 0xc0020e3980}, {0x31e73d8, 0xc0020e3b20}, ...}, ...}}, ...)
	github.com/osmosis-labs/osmosis/v19/x/pool-incentives/module.go:143 +0x9b
github.com/cosmos/cosmos-sdk/types/module.(*Manager).ExportGenesisForModules(_, {{0x32066a8, 0xc0000560b0}, {0x321bb00, 0xc00a4c5d00}, {{0x0, 0x0}, {0x0, 0x0}, 0x249173, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.47.4/types/module/module.go:350 +0x285
github.com/osmosis-labs/osmosis/v19/app.(*OsmosisApp).ExportAppStateAndValidators(0xc0014ad200, 0x0, {0x0?, 0x0?, 0x0?}, {0x47c7c18, 0x0, 0x0})
	github.com/osmosis-labs/osmosis/v19/app/export.go:29 +0x1c5
github.com/osmosis-labs/osmosis/v19/cmd/osmosisd/cmd.createOsmosisAppAndExport({0x3207c18, 0xc0006a8420}, {0x321ac98, 0xc0002720d8}, {0x0, 0x0}, 0xffffffffffffffff, 0x18?, {0x47c7c18, 0x0, ...}, ...)
	github.com/osmosis-labs/osmosis/v19/cmd/osmosisd/cmd/root.go:631 +0x2b4
github.com/cosmos/cosmos-sdk/server.ExportCmd.func1(0xc00067f500?, {0xc00158fc20?, 0x0?, 0x2?})
	github.com/cosmos/cosmos-sdk@v0.47.4/server/export.go:73 +0x37c
github.com/spf13/cobra.(*Command).execute(0xc00067f500, {0xc00158fc00, 0x2, 0x2})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc001441200)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.7.0/command.go:985
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc0012f94d0, 0x16})
	github.com/cosmos/cosmos-sdk@v0.47.4/server/cmd/execute.go:36 +0x1eb
main.main()
	./main.go:16 +0x31
```

**Comment by p0mvn** [comment]
Reported similar issue:
https://osmosis-network.slack.com/archives/C029XNL2L9G/p1695150489576199
