### ISSUE TITLE
Unable to create new IBC channels with Osmosis

### ISSUE THREAD

**Issue by spacepotahto** [osmosis-labs/osmosis#665]
### The Problem:
I can't seem to create new IBC channels between Osmosis <-> { Dig, Odin }; I've tried Hermes, Go rly, and TS-relayer (though TS-relayer never really worked in the past either), and they all fail with some sort of error on the Osmosis side. Others also reported the same issues in the IBC Telegram channel when they tried to create new IBC channels between Osmosis <-> { Lum, Chihuahua }. Someone was able to create channels between Chihuahua <-> Bitsong though using Hermes. Note that we are all trying this after the Osmosis v5 upgrade (see also Other Observations at the end). We're all experiencing the following (using Dig as example):

#### Hermes (same results using v0.8.0 and 0.9.0):
```
hermes create channel dig-1 osmosis-1 --port-a transfer --port-b transfer
```
Client creation and init connection happens, and then `gRPC call failed with status: status: Unknown, message: "recovered: parameter UnbondingTime not registered` error. Full error below:
```
2021-12-16T03:20:06.055394Z ERROR ThreadId(21) [osmosis-1] estimate_gas: failed to simulate tx with non-recoverable error: gRPC call failed with status: status: Unknown, message: "recovered: parameter UnbondingTime not registered\nstack:\ngoroutine 10606463 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/cosmos/cosmos-sdk/baseapp.newDefaultRecoveryMiddleware.func1({0x198a5c0, 0xc11c2e3a00})\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/baseapp/recovery.go:71 +0x27\ngithub.com/cosmos/cosmos-sdk/baseapp.newRecoveryMiddleware.func1({0x198a5c0, 0xc11c2e3a00})\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/baseapp/recovery.go:39 +0x30\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x198a5c0, 0xc11c2e3a00}, 0xc000547680)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/baseapp/recovery.go:28 +0x37\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x198a5c0, 0xc11c2e3a00}, 0x2606fa0)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/baseapp/recovery.go:33 +0x5e\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1()\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/baseapp/baseapp.go:598 +0xfd\npanic({0x198a5c0, 0xc11c2e3a00})\n\truntime/panic.go:1038 +0x215\ngithub.com/cosmos/cosmos-sdk/x/params/types.Subspace.checkType({{0x0, 0x0}, 0x0, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, 0x0}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/x/params/types/subspace.go:153 +0x179\ngithub.com/cosmos/cosmos-sdk/x/params/types.Subspace.Get({{0x0, 0x0}, 0x0, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, 0x0}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/x/params/types/subspace.go:103 +0x9e\ngithub.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.UnbondingTime(...)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/x/staking/keeper/params.go:12\ngithub.com/cosmos/ibc-go/v2/modules/core/02-client/keeper.Keeper.ValidateSelfClient({{0x25a2690, 0xc000d5e550}, {0x2601df8, 0xc006a04470}, {{0x2601df8, 0xc006a04470}, 0xc000020088, {0x25a2690, 0xc000d5e540}, {0x25a26e0, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/ibc-go/v2@v2.0.0/modules/core/02-client/keeper/keeper.go:310 +0x415\ngithub.com/cosmos/ibc-go/v2/modules/core/03-connection/keeper.Keeper.ConnOpenTry({{0x0, 0x0}, {0x25a2690, 0xc000d5e550}, {{0x2601df8, 0xc006a04470}, 0xc000020088, {0x25a2690, 0xc000d5e540}, {0x25a26e0, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/ibc-go/v2@v2.0.0/modules/core/03-connection/keeper/handshake.go:124 +0x6c5\ngithub.com/cosmos/ibc-go/v2/modules/core/keeper.Keeper.ConnectionOpenTry({{0x0, 0x0}, {0x2601df8, 0xc006a04470}, {{0x25a2690, 0xc000d5e550}, {0x2601df8, 0xc006a04470}, {{0x2601df8, 0xc006a04470}, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/ibc-go/v2@v2.0.0/modules/core/keeper/msg_server.go:168 +0x545\ngithub.com/cosmos/ibc-go/v2/modules/core/03-connection/types._Msg_ConnectionOpenTry_Handler.func1({0x25da038, 0xc0d8e08480}, {0x1bc7a20, 0xc074cb2100})\n\tgithub.com/cosmos/ibc-go/v2@v2.0.0/modules/core/03-connection/types/tx.pb.go:584 +0x78\ngithub.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2.1({0x25da038, 0xc0d8e08450}, {0x4ba1e6, 0x41108b}, 0x1c41180, 0xc0b8c1f038)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/baseapp/msg_service_router.go:113 +0xd5\ngithub.com/cosmos/ibc-go/v2/modules/core/03-connection/types._Msg_ConnectionOpenTry_Handler({0x1c35940, 0xc0001d6f00}, {0x25da038, 0xc0d8e08450}, 0x23674d8, 0xc0ad1f4160)\n\tgithub.com/cosmos/ibc-go/v2@v2.0.0/modules/core/03-connection/types/tx.pb.go:586 +0x138\ngithub.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2({{0x25d9fc8, 0xc000052070}, {0x2606fa0, 0xc074cbc2c0}, {{0xb, 0x1}, {0xc12ecfe510, 0x9}, 0x24abb8, {0x23097927, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/baseapp/msg_service_router.go:117 +0x34f\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs(_, {{0x25d9fc8, 0xc000052070}, {0x2606fa0, 0xc074cbc2c0}, {{0xb, 0x1}, {0xc12ecfe510, 0x9}, 0x24abb8, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/baseapp/baseapp.go:719 +0x46a\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0xc0006031e0, 0x2, {0xc0b4256000, 0x2733, 0x2800})\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/baseapp/baseapp.go:679 +0xa2c\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Simulate(...)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/baseapp/test_helpers.go:22\ngithub.com/cosmos/cosmos-sdk/x/auth/tx.txServer.Simulate({{{0x0, 0x0, 0x0}, {0x2618fb0, 0xc0881ab740}, {0xc0012d48c0, 0x9}, {0x25e3850, 0xc0011ae540}, {0x260c958, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/x/auth/tx/service.go:117 +0x129\ngithub.com/cosmos/cosmos-sdk/types/tx._Service_Simulate_Handler.func1({0x25da038, 0xc0c51e65a0}, {0x1bad840, 0xc07d99aac0})\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/types/tx/service.pb.go:752 +0x78\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).RegisterGRPCServer.func1({0x25da038, 0xc09e1bb6b0}, {0x1bad840, 0xc07d99aac0}, 0xc07d99ab20, 0xc0c7e5eca8)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/baseapp/grpcserver.go:66 +0x40d\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x25da038, 0xc09e1bb6b0}, {0x1bad840, 0xc07d99aac0})\n\tgithub.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a\ngithub.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1({0x25da038, 0xc09e1bb6b0}, {0x1bad840, 0xc07d99aac0}, 0x18, 0xc07d99ab20)\n\tgithub.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/recovery/interceptors.go:33 +0xc8\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x25da038, 0xc09e1bb6b0}, {0x1bad840, 0xc07d99aac0})\n\tgithub.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1({0x25da038, 0xc09e1bb6b0}, {0x1bad840, 0xc07d99aac0}, 0xc0c4d98b01, 0xc0c4d98b58)\n\tgithub.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34 +0xbf\ngithub.com/cosmos/cosmos-sdk/types/tx._Service_Simulate_Handler({0x1b530e0, 0xc09575c680}, {0x25da038, 0xc09e1bb6b0}, 0xc111564660, 0xc09e1bb710)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/types/tx/service.pb.go:754 +0x138\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).RegisterGRPCServer.func2({0x1b530e0, 0xc09575c680}, {0x25da038, 0xc09e1bb6b0}, 0x1c03440, 0xc0691e0900)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/baseapp/grpcserver.go:80 +0xdc\ngoogle.golang.org/grpc.(*Server).processUnaryRPC(0xc095760000, {0x25f66e0, 0xc0000fd680}, 0xc0691e0900, 0xc0957649f0, 0xc088afcfc0, 0x0)\n\tgoogle.golang.org/grpc@v1.42.0/server.go:1210 +0xc8f\ngoogle.golang.org/grpc.(*Server).handleStream(0xc095760000, {0x25f66e0, 0xc0000fd680}, 0xc0691e0900, 0x0)\n\tgoogle.golang.org/grpc@v1.42.0/server.go:1533 +0xa2a\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2()\n\tgoogle.golang.org/grpc@v1.42.0/server.go:871 +0x98\ncreated by google.golang.org/grpc.(*Server).serveStreams.func1\n\tgoogle.golang.org/grpc@v1.42.0/server.go:869 +0x294\n: panic", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "x-cosmos-block-height": "2403256"} }
```

#### Go rly (following https://github.com/notional-labs/notional/blob/master/relaying/rly/Readme.md):
```
rly tx link digosmo -d -o 300s
```
The command times out after about 10s, spits out the following error (I'm running this on an Osmosis node and so the RPC is at localhost), and jams the Osmosis node for a couple minutes:
```
I[2021-12-16|05:13:36.314] - [osmosis-1] -> creating client on osmosis-1 for dig-1 header-height{28983} trust-period(168h0m0s) 
I[2021-12-16|05:13:46.410] Error: querying clients on osmosis-1 failed: post failed: Post "http://localhost:26657": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 
I[2021-12-16|05:13:56.412] - [osmosis-1] -> failed sending transaction: 
{"client_state":{"@type":"/ibc.lightclients.tendermint.v1.ClientState","chain_id":"dig-1","trust_level":{"numerator":"1","denominator":"3"},"trusting_period":"604800s","unbonding_period":"1209600s","max_clock_drift":"600s","frozen_height":{"revision_number":"0","revision_height":"0"},"latest_height":{"revision_number":"1","revision_height":"28983"},"proof_specs":[{"leaf_spec":{"hash":"SHA256","prehash_key":"NO_HASH","prehash_value":"SHA256","length":"VAR_PROTO","prefix":"AA=="},"inner_spec":{"child_order":[0,1],"child_size":33,"min_prefix_length":4,"max_prefix_length":12,"empty_child":null,"hash":"SHA256"},"max_depth":0,"min_depth":0},{"leaf_spec":{"hash":"SHA256","prehash_key":"NO_HASH","prehash_value":"SHA256","length":"VAR_PROTO","prefix":"AA=="},"inner_spec":{"child_order":[0,1],"child_size":32,"min_prefix_length":1,"max_prefix_length":1,"empty_child":null,"hash":"SHA256"},"max_depth":0,"min_depth":0}],"upgrade_path":["upgrade","upgradedIBCState"],"allow_update_after_expiry":true,"allow_update_after_misbehaviour":true},"consensus_state":{"@type":"/ibc.lightclients.tendermint.v1.ConsensusState","timestamp":"2021-12-16T05:13:28.228579687Z","root":{"hash":"GC1O3kQJJFa1H6xn6kn3+MeW5kW57Rty8zbM+hqHTys="},"next_validators_hash":"3856D07BAA91CC8647C1BCBC886D0FCD5575AC18892E8FE643CB5291E937A9B3"},"signer":"osmo1xxwu8gcx64wlrnlwap433hltz8e2pmq4gxph2f"}
E[2021-12-16|05:13:56.413] - [osmosis-1] -> err(post failed: Post "http://localhost:26657": context deadline exceeded (Client.Timeout exceeded while awaiting headers)) 
Error: post failed: Post "http://localhost:26657": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

### Other Observations:
Someone else tried to create new channels between Osmosis <-> Odin a couple days ago (prior to the Osmosis v5 upgrade) and encountered a different error. Today (after the Osmosis v5 upgrade) when I tried it, I get the error above instead like everyone else for other chains, so maybe the Osmosis upgrade has something to do with it.

**Comment by Segfaultd** [comment]
On our side (Lum Network) w've been unable to create paths as well.

Always ended up with timeout exception

**Comment by ctrl-Felix** [comment]
In addition to that:
While chihuahua <> bitsong is working it's not possible to establish a new channel between bitsong <> osmosis. It returns the exact same error

**Comment by ValarDragon** [comment]
What are the hermes and go relayer versions used? We used the default parameters for IBC connections in v1, https://github.com/cosmos/ibc-go/blob/main/modules/core/03-connection/types/params.go, which allows 30 second block times. So I feel like that shouldn't be the issue

**Comment by ctrl-Felix** [comment]
> What is the go relayer versions used?

For me I was using hermes

**Comment by AdityaSripal** [comment]
Looking at the error here:

```2021-12-16T03:20:06.055394Z ERROR ThreadId(21) [osmosis-1] estimate_gas: failed to simulate tx with non-recoverable error: gRPC call failed with status: status: Unknown, message: "recovered: parameter UnbondingTime not registered\nstack:\ngoroutine 10606463 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/cosmos/cosmos-sdk/baseapp.newDefaultRecoveryMiddleware.func1({0x198a5c0, 0xc11c2e3a00})\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/baseapp/recovery.go:71 +0x27\ngithub.com/cosmos/cosmos-sdk/baseapp.newRecoveryMiddleware.func1({0x198a5c0, 0xc11c2e3a00})\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/baseapp/recovery.go:39 +0x30\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x198a5c0, 0xc11c2e3a00}, 0xc000547680)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/baseapp/recovery.go:28 +0x37\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x198a5c0, 0xc11c2e3a00}, 0x2606fa0)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/baseapp/recovery.go:33 +0x5e\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1()\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/baseapp/baseapp.go:598 +0xfd\npanic({0x198a5c0, 0xc11c2e3a00})\n\truntime/panic.go:1038 +0x215\ngithub.com/cosmos/cosmos-sdk/x/params/types.Subspace.checkType({{0x0, 0x0}, 0x0, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, 0x0}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/x/params/types/subspace.go:153 +0x179\ngithub.com/cosmos/cosmos-sdk/x/params/types.Subspace.Get({{0x0, 0x0}, 0x0, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, 0x0}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/x/params/types/subspace.go:103 +0x9e\ngithub.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.UnbondingTime(...)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/x/staking/keeper/params.go:12\ngithub.com/cosmos/ibc-go/v2/modules/core/02-client/keeper.Keeper.ValidateSelfClient({{0x25a2690, 0xc000d5e550}, {0x2601df8, 0xc006a04470}, {{0x2601df8, 0xc006a04470}, 0xc000020088, {0x25a2690, 0xc000d5e540}, {0x25a26e0, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/ibc-go/v2@v2.0.0/modules/core/02-client/keeper/keeper.go:310 +0x415\ngithub.com/cosmos/ibc-go/v2/modules/core/03-connection/keeper.Keeper.ConnOpenTry({{0x0, 0x0}, {0x25a2690, 0xc000d5e550}, {{0x2601df8, 0xc006a04470}, 0xc000020088, {0x25a2690, 0xc000d5e540}, {0x25a26e0, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/ibc-go/v2@v2.0.0/modules/core/03-connection/keeper/handshake.go:124 +0x6c5\ngithub.com/cosmos/ibc-go/v2/modules/core/keeper.Keeper.ConnectionOpenTry({{0x0, 0x0}, {0x2601df8, 0xc006a04470}, {{0x25a2690, 0xc000d5e550}, {0x2601df8, 0xc006a04470}, {{0x2601df8, 0xc006a04470}, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/ibc-go/v2@v2.0.0/modules/core/keeper/msg_server.go:168 +0x545\ngithub.com/cosmos/ibc-go/v2/modules/core/03-connection/types._Msg_ConnectionOpenTry_Handler.func1({0x25da038, 0xc0d8e08480}, {0x1bc7a20, 0xc074cb2100})\n\tgithub.com/cosmos/ibc-go/v2@v2.0.0/modules/core/03-connection/types/tx.pb.go:584 +0x78\ngithub.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2.1({0x25da038, 0xc0d8e08450}, {0x4ba1e6, 0x41108b}, 0x1c41180, 0xc0b8c1f038)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/baseapp/msg_service_router.go:113 +0xd5\ngithub.com/cosmos/ibc-go/v2/modules/core/03-connection/types._Msg_ConnectionOpenTry_Handler({0x1c35940, 0xc0001d6f00}, {0x25da038, 0xc0d8e08450}, 0x23674d8, 0xc0ad1f4160)\n\tgithub.com/cosmos/ibc-go/v2@v2.0.0/modules/core/03-connection/types/tx.pb.go:586 +0x138\ngithub.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2({{0x25d9fc8, 0xc000052070}, {0x2606fa0, 0xc074cbc2c0}, {{0xb, 0x1}, {0xc12ecfe510, 0x9}, 0x24abb8, {0x23097927, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/baseapp/msg_service_router.go:117 +0x34f\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs(_, {{0x25d9fc8, 0xc000052070}, {0x2606fa0, 0xc074cbc2c0}, {{0xb, 0x1}, {0xc12ecfe510, 0x9}, 0x24abb8, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/baseapp/baseapp.go:719 +0x46a\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0xc0006031e0, 0x2, {0xc0b4256000, 0x2733, 0x2800})\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/baseapp/baseapp.go:679 +0xa2c\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Simulate(...)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/baseapp/test_helpers.go:22\ngithub.com/cosmos/cosmos-sdk/x/auth/tx.txServer.Simulate({{{0x0, 0x0, 0x0}, {0x2618fb0, 0xc0881ab740}, {0xc0012d48c0, 0x9}, {0x25e3850, 0xc0011ae540}, {0x260c958, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/x/auth/tx/service.go:117 +0x129\ngithub.com/cosmos/cosmos-sdk/types/tx._Service_Simulate_Handler.func1({0x25da038, 0xc0c51e65a0}, {0x1bad840, 0xc07d99aac0})\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/types/tx/service.pb.go:752 +0x78\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).RegisterGRPCServer.func1({0x25da038, 0xc09e1bb6b0}, {0x1bad840, 0xc07d99aac0}, 0xc07d99ab20, 0xc0c7e5eca8)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/baseapp/grpcserver.go:66 +0x40d\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x25da038, 0xc09e1bb6b0}, {0x1bad840, 0xc07d99aac0})\n\tgithub.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a\ngithub.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1({0x25da038, 0xc09e1bb6b0}, {0x1bad840, 0xc07d99aac0}, 0x18, 0xc07d99ab20)\n\tgithub.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/recovery/interceptors.go:33 +0xc8\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x25da038, 0xc09e1bb6b0}, {0x1bad840, 0xc07d99aac0})\n\tgithub.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1({0x25da038, 0xc09e1bb6b0}, {0x1bad840, 0xc07d99aac0}, 0xc0c4d98b01, 0xc0c4d98b58)\n\tgithub.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34 +0xbf\ngithub.com/cosmos/cosmos-sdk/types/tx._Service_Simulate_Handler({0x1b530e0, 0xc09575c680}, {0x25da038, 0xc09e1bb6b0}, 0xc111564660, 0xc09e1bb710)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/types/tx/service.pb.go:754 +0x138\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).RegisterGRPCServer.func2({0x1b530e0, 0xc09575c680}, {0x25da038, 0xc09e1bb6b0}, 0x1c03440, 0xc0691e0900)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/baseapp/grpcserver.go:80 +0xdc\ngoogle.golang.org/grpc.(*Server).processUnaryRPC(0xc095760000, {0x25f66e0, 0xc0000fd680}, 0xc0691e0900, 0xc0957649f0, 0xc088afcfc0, 0x0)\n\tgoogle.golang.org/grpc@v1.42.0/server.go:1210 +0xc8f\ngoogle.golang.org/grpc.(*Server).handleStream(0xc095760000, {0x25f66e0, 0xc0000fd680}, 0xc0691e0900, 0x0)\n\tgoogle.golang.org/grpc@v1.42.0/server.go:1533 +0xa2a\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2()\n\tgoogle.golang.org/grpc@v1.42.0/server.go:871 +0x98\ncreated by google.golang.org/grpc.(*Server).serveStreams.func1\n\tgoogle.golang.org/grpc@v1.42.0/server.go:869 +0x294\n: panic", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "x-cosmos-block-height": "2403256"} }
```

It looks like `UnbondingTime` isn't registered which is a parameter of the staking module that the connection keeper uses.

https://github.com/cosmos/ibc-go/blob/main/modules/core/03-connection/keeper/handshake.go#L124

https://github.com/cosmos/ibc-go/blob/2273ef39fd461eb2c5977a8dcaa16e44a4e97251/modules/core/02-client/keeper/keeper.go#L310

So my guess is that this is an issue with how the app is wired up.

I believe the staking keeper that is passed into the clientkeeper does not have its parameters registered correctly. 

This reminds me of a similar problem I had in interchain-security. See these commits:

https://github.com/cosmos/interchain-security/pull/25/commits/a54d1374a6e72f2b85aabef45f540bc1de9fa5fc

https://github.com/cosmos/interchain-security/pull/25/commits/368b5116e63ec93d0fbf5e934737a2a46d7d30b1

I don't know if those commits help. But i would look to see if there's potentially an issue of IBC receiving the staking keeper before the parameters are registered in `app.go`

**Comment by AdityaSripal** [comment]
I would try moving this line: https://github.com/osmosis-labs/osmosis/blob/main/app/app.go#L481

above the IBC Keeper creation and see if it works

**Comment by sunnya97** [comment]
Hoods shouldn't be what sets params

**Comment by AdityaSripal** [comment]
Yea but i think you're replacing the staking keeper here. Annoying pointer issue i think

**Comment by colin-axner** [comment]
It looks like the IBC Keeper is being passed the uninitialized staking keeper since the staking keeper is created as a variable and not set to app.StakingKeeper

https://github.com/osmosis-labs/osmosis/blob/0af385c652ac93aac5826813bd7ae992248494b9/app/app.go#L329

https://github.com/osmosis-labs/osmosis/blob/0af385c652ac93aac5826813bd7ae992248494b9/app/app.go#L440

**Comment by AdityaSripal** [comment]
Ahh yea, i think colin's correct

**Comment by AdityaSripal** [comment]
app.go is by far the worst part of cosmos developer ux

**Comment by sunnya97** [comment]
Agggghhhhh

That's so annoying.  Yeah...  That seems likes it's probably it.

**Comment by colin-axner** [comment]
Since the StakingKeeper params are not accessible to the IBC Keeper, no connection handshake can succeed until the fix is upgraded to. That is the extent of the damage. Existing clients/connections can continue to be maintained and packet flow won't be disrupted. 

We use the staking params, UnbondingTime and GetHistoricalInfo. UnbondingTime is used for self verification of the client state in ConnOpenTry/Ack and GetHistoricalInfo is used for self verification of the consensus state in ConnOpenTry/Ack. 

We will add [defensive checks](https://github.com/cosmos/ibc-go/issues/641) to our codebase to hopefully avoid a reoccurence of this issue

**Comment by sunnya97** [comment]
Fixed in upgrade
