### ISSUE TITLE
gentx appears broken on v5

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#667]
We've seen a few reports of gentxs being broken on the v5 binary. We should investigate and fix it. I don't get how the error message relates to the line the error was returned at though...

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x135747c]

goroutine 1 [running]:
github.com/osmosis-labs/osmosis/x/pool-incentives/types.ValidateGenesis(0xc001323620)
        github.com/osmosis-labs/osmosis/x/pool-incentives/types/genesis.go:53 +0x7c
github.com/osmosis-labs/osmosis/x/pool-incentives.AppModuleBasic.ValidateGenesis({{0x40000000000001c, 0xf3ffffffffffffff}}, {0x25e1830, 0xc00115ac00}, {0x6, 0xc0000cee08}, {0xc00029c300, 0xb6, 0xc0})
        github.com/osmosis-labs/osmosis/x/pool-incentives/module.go:57 +0xf2
github.com/cosmos/cosmos-sdk/types/module.BasicManager.ValidateGenesis(0xc0005ea000, {0x25e1830, 0xc00115ac00}, {0x7d22fa7681b8, 0xc000ee9c40}, 0x7ffc6d8ed3d2)
        github.com/cosmos/cosmos-sdk@v0.44.3/types/module/module.go:103 +0x117
github.com/cosmos/cosmos-sdk/x/genutil/client/cli.GenTxCmd.func1(0xc0011ce000, {0xc001194500, 0x2, 0x5})
        github.com/cosmos/cosmos-sdk@v0.44.3/x/genutil/client/cli/gentx.go:96 +0x465
github.com/spf13/cobra.(*Command).execute(0xc0011ce000, {0xc0011944b0, 0x5, 0x5})
        github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc001186000)
        github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.2.1/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.2.1/command.go:895
github.com/osmosis-labs/osmosis/cmd/osmosisd/cmd.Execute(0xc0000001a0)
        github.com/osmosis-labs/osmosis/cmd/osmosisd/cmd/root.go:150 +0xf4
main.main()
        github.com/osmosis-labs/osmosis/cmd/osmosisd/main.go:13 +0x25
Error: failed to get genesis app state from config: open {file name redacted"
```

**Comment by sunnya97** [comment]
My scripts work fine
```
rm -rf ~/.osmotest
./build/osmosisd init validator --chain-id osmotest-1 --home ~/.osmotest
./build/osmosisd keys add validator --keyring-backend test --home ~/.osmotest
./build/osmosisd prepare-genesis mainnet osmotest-1 --home ~/.osmotest
./build/osmosisd add-genesis-account $(osmosisd keys show validator -a --keyring-backend test --home ~/.osmotest) 10000000ion,100000000000000uosmo --home ~/.osmotest
./build/osmosisd gentx validator 50000000000000uosmo --chain-id osmotest-1 --keyring-backend test --home ~/.osmotest
./build/osmosisd collect-gentxs --home ~/.osmotest
./build/osmosisd start --home ~/.osmotest
```

@UnityChaos said that by adding the `osmosisd prepare-genesis mainnet osmotest-1` to her script, it worked as well

**Comment by UnityChaos** [comment]
Looks like it's the Distrinfo InitGenesis bug again, guess the fix didn't get merged into the v5.x branch. `prepare-genesis` fixes it by setting that before gentx happens.

**Comment by ValarDragon** [comment]
This has been fixed to my knowledge!
