### ISSUE TITLE
Authz granting of delegate permissions does not work from ledger

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#827]
(Note authz generic mode works, and you can use that to get the functionality of delegate to any validator)

I haven't checked, but I think this should only be a problem from ledger (since amino). I think the fix could be state breaking though. Need to look into why this isn't getting added to the amino interface registration.

Failing command:

```
osmosisd tx authz grant {grantee} delegate --from=granter --deny-validators="{pick any valoper}"

confirm transaction before signing and broadcasting [y/N]: y
panic: Unregistered interface types.isStakeAuthorization_Validators

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*LegacyAmino).MustMarshalJSON(...)
	github.com/cosmos/cosmos-sdk@v0.44.5/codec/amino.go:154
github.com/cosmos/cosmos-sdk/x/authz.MsgGrant.GetSignBytes({{0xc0014cfdd0, 0x2b}, {0xc0014cfe60, 0x2b}, {0xc0014eb7a0, {0x0, 0xedb70a7de, 0x7283fe0}}})
	github.com/cosmos/cosmos-sdk@v0.44.5/x/authz/msgs.go:82 +0xf4
github.com/cosmos/cosmos-sdk/x/auth/legacy/legacytx.StdSignBytes({0xc00140f510, 0x9}, 0x155d7, 0x36f, 0x0, {{0x0, 0x1f, 0x1f}, 0xc00161e138}, {0xc000694250, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.44.5/x/auth/legacy/legacytx/stdsign.go:61 +0x297
github.com/cosmos/cosmos-sdk/x/auth/tx.signModeLegacyAminoJSONHandler.GetSignBytes({}, 0x161e200, {{0xc00140f510, 0xc00161e240}, 0x400e654, 0x2}, {0x616eb00, 0xc00155c880})
	github.com/cosmos/cosmos-sdk@v0.44.5/x/auth/tx/legacy_amino_json.go:49 +0x1a7
github.com/cosmos/cosmos-sdk/x/auth/signing.SignModeHandlerMap.GetSignBytes({0x1, {0xc0012e5810, 0x2, 0x2}, 0xc00133b440}, 0x6182a90, {{0xc00140f510, 0x9}, 0x155d7, 0x36f}, ...)
...
```

Help investigating this would definitely be appreciated!

**Comment by ValarDragon** [comment]
I saw in discord that this is an issue from the SDK thats slated for fix in SDK v0.46
