### ISSUE TITLE
osmosis drops peers with unable to delete version with 1 active readers

### ISSUE THREAD

**Issue by kucharskim** [osmosis-labs/osmosis#919]
Simple restart helps, but otherwise it just doesn't progresses with chain height:
```
osmosis_1  | 3:33AM INF client state updated client-id=07-tendermint-1666 height=1-997700 module=x/ibc/client
osmosis_1  | 3:33AM INF client state updated client-id=07-tendermint-1666 height=1-997700 module=x/ibc/client
osmosis_1  | 3:33AM INF executed block height=3299020 module=state num_invalid_txs=7 num_valid_txs=10
osmosis_1  | 3:33AM ERR CONSENSUS FAILURE!!! err="unable to delete version 3299000 with 1 active readers" module=consensus stack="goroutine 2108 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/tendermint/
tendermint/consensus.(*State).receiveRoutine.func2()\n\tgithub.com/tendermint/tendermint@v0.34.15/consensus/state.go:726 +0x4c\npanic({0x1a5f2a0, 0xc016520f00})\n\truntime/panic.go:1038 +0x215\ngithub.com/cosmos/cosmos-sdk/store/rootmult
i.(*Store).pruneStores(0xc001378320)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.5/store/rootmulti/store.go:424 +0x1b6\ngithub.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).Commit(0xc001378320)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.5/store/ro
otmulti/store.go:398 +0x175\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc0005396c0)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.5/baseapp/abci.go:307 +0x231\ngithub.com/tendermint/tendermint/abci/client.(*localClient).CommitSync(
0xc00121c1e0)\n\tgithub.com/tendermint/tendermint@v0.34.15/abci/client/local_client.go:264 +0xb6\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).CommitSync(0x0)\n\tgithub.com/tendermint/tendermint@v0.34.15/proxy/app_conn.go:9
3 +0x22\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).Commit(_, {{{0xb, 0x1}, {0xc0072f8419, 0x7}}, {0xc0072f8430, 0x9}, 0x1, 0x3256cc, {{0xc040cc7260, ...}, ...}, ...}, ...)\n\tgithub.com/tendermint/tendermint@v0.34.15/state/
execution.go:228 +0x269\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x1}, {0xc0072f8419, 0x7}}, {0xc0072f8430, 0x9}, 0x1, 0x3256cc, {{0xc040cc7260, ...}, ...}, ...}, ...)\n\tgithub.com/tendermint/tender
mint@v0.34.15/state/execution.go:180 +0x6ee\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc005536000, 0x3256cc)\n\tgithub.com/tendermint/tendermint@v0.34.15/consensus/state.go:1635 +0x9fd\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc005536000, 0x3256cc)\n\tgithub.com/tendermint/tendermint@v0.34.15/consensus/state.go:1546 +0x305\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit.func1()\n\tgithub.com/tendermint/tendermint@v0.34.15/consensus/state.go:1481 +0x87\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit(0xc005536000, 0x3256cc, 0x0)\n\tgithub.com/tendermint/tendermint@v0.34.15/consensus/state.go:1519 +0xc06\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0xc005536000, 0xc030d18e60, {0xc0098b60c0, 0x28})\n\tgithub.com/tendermint/tendermint@v0.34.15/consensus/state.go:2132 +0xb6e\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc005536000, 0xc030d18e60, {0xc0098b60c0, 0xc031aa2600})\n\tgithub.com/tendermint/tendermint@v0.34.15/consensus/state.go:1930 +0x2c\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc005536000, {{0x25a2200, 0xc038bdc390}, {0xc0098b60c0, 0x0}})\n\tgithub.com/tendermint/tendermint@v0.34.15/consensus/state.go:838 +0x40b\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc005536000, 0x0)\n\tgithub.com/tendermint/tendermint@v0.34.15/consensus/state.go:762 +0x419\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\tgithub.com/tendermint/tendermint@v0.34.15/consensus/state.go:378 +0x12f\n"
osmosis_1  | 3:33AM INF Stopping baseWAL service impl={"Logger":{}} module=consensus wal=/osmosis/.osmosisd/data/cs.wal/wal
osmosis_1  | 3:33AM INF Stopping Group service impl={"Dir":"/osmosis/.osmosisd/data/cs.wal","Head":{"ID":"2VuwtdkuQDVm:/osmosis/.osmosisd/data/cs.wal/wal","Path":"/osmosis/.osmosisd/data/cs.wal/wal"},"ID":"group:2VuwtdkuQDVm:/osmosis/.osmosisd/data/cs.wal/wal","Logger":{}} module=consensus wal=/osmosis/.osmosisd/data/cs.wal/wal
osmosis_1  | 3:33AM INF Timed out dur=3000 height=3299020 module=consensus round=0 step=3
osmosis_1  | 3:33AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=20 numToDial=0
osmosis_1  | 3:34AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=20 numToDial=0
osmosis_1  | 3:34AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=20 numToDial=0
osmosis_1  | 3:35AM ERR Failed to write PacketMsg err="write tcp 172.19.0.2:37388->178.62.16.45:26656: write: broken pipe" module=p2p peer={"id":"bdbb254d8c548db8092077481c22948564fe23ad","ip":"178.62.16.45","port":26656}
osmosis_1  | 3:35AM INF Stopping MConnection service impl={"Logger":{}} module=p2p peer={"id":"bdbb254d8c548db8092077481c22948564fe23ad","ip":"178.62.16.45","port":26656}
osmosis_1  | 3:35AM ERR Stopping peer for error err="write tcp 172.19.0.2:37388->178.62.16.45:26656: write: broken pipe" module=p2p peer={"Data":{},"Logger":{}}
osmosis_1  | 3:35AM INF Stopping Peer service impl={"Data":{},"Logger":{}} module=p2p peer={"id":"bdbb254d8c548db8092077481c22948564fe23ad","ip":"178.62.16.45","port":26656}
osmosis_1  | 3:35AM INF Stopping gossipVotesRoutine for peer module=consensus peer={"Data":{},"Logger":{}}
osmosis_1  | 3:35AM INF Stopping gossipDataRoutine for peer module=consensus peer={"Data":{},"Logger":{}}
osmosis_1  | 3:35AM INF Stopping queryMaj23Routine for peer module=consensus peer={"Data":{},"Logger":{}}
osmosis_1  | 3:35AM INF Saving AddrBook to file book=/osmosis/.osmosisd/config/addrbook.json module=p2p size=1282
osmosis_1  | 3:35AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=19 numToDial=1
```

**Comment by kucharskim** [comment]
```
$ osmosisd version
6.1.0
```

**Comment by kucharskim** [comment]
https://generic.mp/r/lqlh-q4ao-dmi4-lavb-lxsi-i7rw-jdzi/

**Comment by kucharskim** [comment]
Again:
```
osmosis_1  | 8:54AM ERR CONSENSUS FAILURE!!! err="unable to delete version 3302000 with 1 active readers"
```

**Comment by kucharskim** [comment]
This instance has `pruning = "everything"` setup.

**Comment by ValarDragon** [comment]
I'd guess that you have snapshots enabled on this. You have to keep snapshots off with pruning=everything

Can you double check what your snapshot settings are?
